
#FILLERS PART 6
questions=		[   ["Fillers going to be start in 30 secs...choose the option which provides the correct set of words"],




			 			 ["Q.151.(1) Confidence was increasing that men, through and effective action, could __________ their existence and even prolong their lives. (2) Others, perhaps with greater __________, wanted the struggle to continue in order to countryside. _______ the conditions of the peasants in the (a) prodigal, fortify (b) discrimination, vitiate (c) improvidence, remediate (d) foresight, ameliorate (e) shortsightedness, blemish"],
			 			 ["Q.152. (1) A shopkeeper with red pimples on his cheeks near the nose, and a calm, __________, calculating expression on his plump face, hurriedly and approached the officer, swinging his arms. (II) The party has been __________ with its representatives and today some of them have become__________ rich and some even preach a gospel of wealth. (a) relentless, modestly (b) persistent, ostentatiously (c) faltering, calmly (d) vacillating, plainly (e) hesitant, moderately"],
			 			 ["Q.153. (I) The legal system currently punishes the most __________ forms of child abuse and neglect, but such crimes are __________ to prove. (II) Demonetization was the most step taken by Modi government and it made the life of common people __________ for next few months. (a) modest, brutal (b) concealed, facile (c) unobtrusive, comfortable (d) inconspicuous, superficial (e) egregious, arduous"],
			 			 ["Q.154. (I) His plans, probably not very definite, were disturbed by an __________ message from the queen, ordering him not to return to England without her___. (II) The events which were taking place in Europe made it to send home a part of the army of Africa, and Medea gave his __________ for the same. (a) dispensable, revocation (b) unimportant, injunction (c) imperative, consent (d) discretionary, deterrence (e) inconsequential, embargo"],
			 			 ["Q.155. (I) The _____ modern being is a bit like Howard Roark, who in Ayn Rand’s The Fountainhead sits atop a metaphorical mountain __________ to view life from a distance. (II) For the subordinates, the_____ managerial role was to create a supportive environment within which they could prosper professionally without being _____by anyone. (a) quintessential, condemned (b) substandard, endorsed (c) atrocious, eulogized (d) ordinary, consecrated (e) mediocre, venerated"],
			 			 ["Q.156. [I] The question that had _____ Pierre on the Mozhaysk hill and all that day now seemed to him quite clear and completely _____. [II] For the ancients these _____ questions were _____ by a belief in the direct participation of the Deity in human affairs. (a) flustered, vague (b) answered, tangled (c) baffled, unsettled (d) perturbed, solved (e) procrastinated, mystery"],
			 			 ["Q.157. [I] Land left _____ was occupied by colonial farmers, and over 2000 German _____ were introduced by Sir George and settled along the frontier (1858-1859). [II] The building was _____ for decades after that, _____ who didn’t pass the required intelligence tests were moved to these rooms until their eventual deportations. (a) engaged, refugees (b) populated, fighters (c) reliable, revolutionaries (d) occupied, soldiers (e) derelict, immigrants"],
			 			 ["Q.158. [I] Some of the employees, in their_____ to win the business of wealthy Americans with a _____ for fibbing to the taxman, seem to have confused discretion with spycraft. [II] There will always be some employees with the _____ to pursue profits with minimal regard for larger social consequences; however, this _____ need not be fashionable. (a) zeal, predilection (b) enthusiasm, animosity (c) competition, antipathy (d) sloth, propensity (e) lethargy, druthers"],
			 			 ["Q.159. [I] Mr. Bonar Law was whole-heartedly in favour of the _____ , and frequently _____ friends to remain true to it his Conservative [II] As a single person, I find it very difficult to fight the _____ of my neighbors who are against the installation of a neighborhood charter, so I solemnly _____the higher authorities to stand in my support. (a) alliance, impoverished (b) union, trespassed (c) combination, appealed (d) affiliation, declined (e) coalition, adjured"],
			 			 ["Q.160. [I] After a poor display in a tour match, in which Pathan was hit for 70 runs in 12 overs and appeared _____ , he was dropped from the Test team as V. R. V. Singh became the third pace bowler, _____ a news channel. [II] Most citizens of Juarez are somewhat _____ with the routinely _____ accounts of killings by rival drug lords or dueling gang members. (a) bored, created (b) jaded, reported (c) energized, declared (d) fatigued, translated (e) excited, recorded Directions (161-165): In each of the questions given below, a paragraph is given which has some blanks and those blanks must be filed with the same word out of five words given below it. You must choose that same as your answer and fill up the blanks with that appropriate answer."],
			 			 ["Q.161. After a muted Onam, Kerala woke up on Sunday to the reality of providing _____to the humungous number of stranded people and to the enormity of rehabilitation and restoration of normal life. According to Chief Minister Pinarayi Vijayan, who held a review of the _____ and rehabilitation work on Sunday, 462456 persons are still housed in 1435 _____ camps. (a) Nonchalance (b) Hindrance (c) Succor (d) Deluge (e) Torrent"],
			 			 ["Q.162. Four fresh recruits planning to enter Pakistan-occupied Kashmir (PoK) for arms training were __________ in the frontier district of Kupwara on Sunday. The four were __________ after a brief gunfight in the Kupwara district. Extreme restraint was exercised, and opportunity was given to the militants to surrender. The four surrendered and subsequently . (a) zapped (b) killed (c) spawned (d) arrested (e) eliminated"],
			 			 ["Q.163. Former PM Manmohan Singh has written to Prime Minister Narendra Modi saying that the historic Teen Murti complex, ___________ to the memory of Jawaharlal Nehru, should be left undisturbed. It comes in the wake of reports that the Modi government wants to create a museum ___________ to all Prime Ministers in the Teen Murti complex. Even his political rivals ___________ their reverence to his distinctiveness and greatness, said Dr. Singh. (a) posited (b) dedicated (c) belonged (d) imprinted (e) altered"],
			 			 ["Q.164. Chief Justice of India '(cJI) Justice Dipak Misra on Sunday called upon law students to engage in the practice of 'cause lawyering and develop the idea of serviceability to law by taking up pro bono cases to protect human ______________, _____ of individuals and _______________ of under-privileged. (a)succor (b) travesty (c) equanimity (d) deluge (e) rights"],
			 			 ["Q.165. Mr. Bhagat, a loco pilot of the Bamanhat-Siliguri Jn. passenger train applied the brakes after spotting a __________ of elephants close to the track between Sivok and Gumla stations in northern West Bengal on August 24 evening. My assistant [Mr. Kumar] spotted the_____ at about 5.35 p.m. The __________ was not visible from my side of the locomotive because of a bend in the track. (a) herd (b) pronouncement (c) army (d) fleet (e) swarm "],
						 
						 
			 			 ["Q.166. (1) Never mind that the Turkish supremo did his best to_____the Kurdish-led defence of Kobani against an IS assault. (2) To do what the superior power requires of him, he must ____________ his inclinations. (3) Turkish security forces have been involved in a longrunning campaign to_____ Daesh attacks. (I) impede (II) thwart (III) inhibit (IV) facilitate (a) Only (I) (b) Both (I) and (II) (c) Both (II) and (IV) (d) Only (I), (II) and (III) (e) All (I), (II), (III) and (IV)"],
			 			 ["Q.167. (1) Mathletics is described as an engaging, supportive online learning resource ____________ at primary school level maths curriculum, allowing children to play live mental arithmetic games against other children from all over the world. (2) Military force would be applied in a purer form and _____________ primarily against the military capabilities of an opponent. (3) These definitions were specifically ____________ at Indigenous Australians, and were prevalent on the majority of the word's entries up until recently. (I) targeted (II) aimed (III) directed (IV) intended (a) Only (I) (b) Only (II) (c) Both (III) and (IV) (d) Only (I), (III) and (IV) (e) All (I), (II), (III) and (IV)"],
			 			 ["Q.168. (1) The Museum of Geographical Heritage is among recent initiatives that promise to expand the scope of the museum beyond a _______________. (2) As may be imagined he was a ________________ of much valuable and varied information. (3) Brush with Fame is a chance for readers of The Canton _______________ to share photos of their chance encounters with celebrities and the famous folks who walk among us. (I) shade (II) repository (III) wealth (IV) dungeon (a) Only (II) (b) Both (I) and (III) (c) Both (II) and (III) (d) Both (I) and (IV) (e) All (I), (II), (III) and (IV)"],
			 			 ["Q.169. (1) Contrary to the popular belief that people tend to be more satisfied with an increase in their wage, a new study suggests that it may be temporary and not have a_____ effect on job satisfaction. (2) Hermione knew something of the Neapolitan men. ______________ infidelities of (3) Inside the house she heard the hammering. ________________, energetic sound of (I) persistent (II) lingering (III) intermittent (IV) yielding (a) Only (I) (b) Both (I) and (II) (c) Only (I), (II) and (IV) (d) Only (II), (III) and (IV) (e) All (I), (II), (III) and (IV)"],
			 			 ["Q.170. (1) It has been a victory for democracy in Hong Kong, and the signal emitted by the island nation’s highest court must be particularly _______________ for China. (2) At that instant a dull but roof overhead. _________________ thump was heard on the (3) Asserting that the inaugural edition of the Khelo India School Games has been a _________________ success, Sports minister Rajyavardhan Singh Rathore hoped on Tuesday that it will help to improve India's performance in the international arena. (I) emphatic (II) phenomenal (III) resounding (IV) massive (a) Only (IV) (b) Both (II) and (III) (c) Only (I), (II) and (III) (d) Only (II), (III) and (IV) (e) All (I), (II), (III) and (IV)  "],
			 			 ["Q.171. (1) The alliance between the PDP and the BJP in Jammu and Kashmir began as an act of necessity, persisted due to sunk-costs and political ____________, and has finally ended as a result of political ___________. (2) Burke carried into the world of theory those politics of ___________ as well as originator. ____________ of which Walpole had been the practical (a) infeasibility, disadvantage (b) impracticality, appropriateness (c) expediency, opportunism (d) unwisdom, timelessness (e) dilemma, losses"],
			 			 ["Q.172. (1) One can understand the banks’ ____________ to switch to the lower MCLR-based rates, given the multiple pressures they face, including record levels of NPAs, and treasury losses. (2) But as time progressed, his obvious ____________ to arranged marriage presented a problem in front of his parents. (a) willingness, astonishing (b) assurance, ordinary (c) certainty, prosaic (d) suspicion, forgettable (e) reluctance, noteworthy"],
			 			 ["Q.173. (1) Traditionally, the services of outside experts were ____________ through consultative processes, a practice quite with the erstwhile Planning Commission and to some extent with its new avatar, the NITI Aayog. (2) Alexander ____________ himself of the defeat of the French to break the power of the Orsini, following the general tendency of all the princes of the day to crush the feudatories and establish a centralized despotism. (a) satisfied, restricted (b) availed, widespread (c) missed, compelled (d) hindered, restrained (e) bestowed, circumscribed"],
			 			 ["Q.174. (1) Democrats and Republicans alike have expressed deep concern about the ethics of using children, ______________facing from separation from their parents, to______________ further undocumented border crossings. (2) Not every employee is prepared for such ____________, even though studies show that low price stocks____________ investments, in the long run. (a) equanimity, animate (b) complacence, distress (c) contentment, galvanize (d) trauma, dissuade (e) alleviation, invigorate"],
			 			 ["Q.175. (1) Farmer’s collectives such as Farmer Producer Organizations need to be _______and these would be critical to_______ the ZBNF (Zero Budget Natural Farming) programme. (2) Only a well ____________ military dictatorship would be capable of ____________ an ordered society in the aftermath of a severe conflict. (a) confuted, bypassing (b) embedded, nurturing (c) established, sustaining (d) furnished, repudiating (e) authenticated, resisting  "],
			 			 ["Q.176. More children growing up in a world so increasingly diverse that stock racial identities no longer ________. (a) call off (b) hold up (c) leave out (d) blow up (e) bring up"],
			 			 ["Q.177. A pleasant spoken young constable arrived at Riverview with a warrant and asked if he might_______ the boat. (a) turn up (b) take down (c) make out (d) make up (e) look over"],
			 			 ["Q.178. We came into the theatre at about two for a_______, Matt came in as well and he was struggling with his voice. (a) put out (b) put up (c) run away (d) run through  (e) run into"],
			 			 ["Q.179. Jet needs to urgently __________its cost strategy as it does not have enough funds to continue operations for more than two months. (a) work out (b) warm up (c) wake up (d) turn down (e) take out"],
			 			 ["Q.180. Cameron Borthwick-Jackson hopes to make up for lost time and _________________his best as the Manchester United left-back begins his season-long loan at Scunthorpe. (a) get up (b) get back at (c) get back to (d) get along with (e) get around "],
			 			 ["Now Over!!"]
 
 ]
 
 
 




#FILLERS  solution PART 6

sol= [	"Lets Start!",

		"Ans.151. (d) 'foresight, ameliorate' is the pair of words that fits in the two sentences to make both the sentences grammatically and contextually complete. Hence, option (d) is the most appropriate choice. Foresight means the ability to predict what will happen or be needed in the future. Ameliorate means make (something bad or unsatisfactory) better. Prodigal means spending money or using resources freely and recklessly; wastefully extravagant Vitiate means spoil or impair the quality or efficiency of. Improvidence means the quality or state of not foreseeing and providing for the future Remediate means to settle (disputes, strikes, etc.) as an intermediary between parties; reconcile. Blemish means a small mark or flaw which spoils the appearance of something. ",
		"Ans.152. (b); ‘persistent, ostentatiously’ is the pair of words that fits in the two sentences to make both the sentences grammatically and contextually complete. Hence, option (b) is the most appropriate choice. Persistent means continuing firmly or obstinately in an opinion or course of action in spite of difficulty or opposition. Ostentatiously means in a pretentious or showy way designed to impress. Relentless means unceasingly intense. Modestly means in an unassuming manner; without vanity or arrogance. Faltering means losing strength or momentum. Vacillating means wavering between different opinions or actions; irresolute. ",
		"Ans.153. (e); ‘egregious, arduous’ is the pair of words that fits in the two sentences to make both the sentences grammatically and contextually complete. Hence, option (e) is the most appropriate choice. Egregious means shocking. Arduous means difficult and tiring. Brutal means savagely violent. Facile means ignoring the true complexities of an issue; superficial Unobtrusive means not conspicuous or attracting attention. Inconspicuous means not clearly visible or attracting attention. Superficial means appearing to be true or real only until examined more closely. ",
		"Ans.154. (c); ‘imperative, consent’ is the pair of words that fits in the two sentences to make both the sentences grammatically and contextually complete. Hence, option (c) is the most appropriate choice. Imperative means of vital importance; crucial Consent means permission for something to happen or agreement to do something. Dispensable means able to be replaced or done without; superfluous. Revocation means the official cancellation of a decree, decision, or promise. Injunction means an authoritative warning or order. Discretionary means available for use at the discretion of the user. Deterrence means the action of discouraging an action or event through instilling doubt or fear of the consequences. Inconsequential means not important or significant. Embargo means an official ban on any activity. ",
		"Ans.155. (a); ‘quintessential, condemned’ is the pair of words that fits in the two sentences to make both the sentences grammatically and contextually complete. Hence, option (a) is the most appropriate choice. Quintessential means representing the most perfect or typical example of a quality or class. Condemned means express complete disapproval of Substandard means below the usual or required standard. Endorsed means declare one's public approval or support of. Atrocious means horrifyingly wicked. Eulogized means praise highly in speech or writing. Consecrated means make or declare (something, typically a church) sacred Venerated means regard with great respect. ",
		"Ans.156. (d); The most appropriate set of words that appropriately fit in the context of the paragraph is ‘perturbed, solved’. ‘perturbed’ is an adjective which means anxious or unsettled; upset. Moreover, ‘solved’ is a verb which means to find an answer to, explanation for, or means of effectively dealing with (a problem or mystery). Since, all the other sets of words fail to form a comprehensive sentence, option (d) becomes the most suitable answer choice. Flustered means make (someone) agitated or confused. Tangled means twisted together untidily; matted. Baffled means totally bewilder or perplex. Procrastinated means delay or postpone action; put off doing something. ",
		"Ans.157. (e); The most appropriate set of words that appropriately fit in the context of the paragraph is ‘derelict, immigrants’. ‘Derelict’ is an adjective which means in a very poor condition as a result of disuse and neglect. Moreover, ‘immigrants’ is a noun which means a person who comes to live permanently in a foreign country. Since, all the other sets of words fail to form a comprehensive sentence, option (e) becomes the most suitable answer choice. ",
		"Ans.158. (a); The most appropriate set of words that appropriately fit in the context of the paragraph is ‘zeal, predilection’. ‘Zeal’ is a noun which means great energy or enthusiasm in pursuit of a cause or an objective. Moreover, ‘predilection’ is a noun which means a preference or special liking for something; a bias in favour of something. Since, all the other sets of words fail to form a comprehensive sentence, option (a) becomes the most suitable answer choice. Animosity means strong hostility. Antipathy means a deep-seated feeling of aversion. Sloth means reluctance to work or make an effort; laziness. Propensity means an inclination or natural tendency to behave in a particular way. ",
		"Ans.159. (e); The most appropriate set of words that appropriately fit in the context of the paragraph is ‘coalition, adjured’. ‘Coalition’ is a noun which means a temporary alliance for combined action, especially of political parties forming a government. Moreover, ‘adjured’ is a verb which means urge or request (someone) solemnly or earnestly to do something. Since, all the other sets of words fail to form a comprehensive sentence, option (e) becomes the most suitable answer choice. ",
		"Ans.160. (b); The most appropriate set of words that appropriately fit in the context of the paragraph is ‘jaded, reported’. ‘Jaded’ is an adjective which means bored or lacking enthusiasm, typically after having had too much of something. Moreover, ‘reported’ is a verb which means give a spoken or written account of something that one has observed, heard, done, or investigated. Since, all the other sets of words fail to form a comprehensive sentence, option (b) becomes the most suitable answer choice. Fatigued means cause (someone) to feel exhausted. Energized means give vitality and enthusiasm to. ",
		"Ans.161. (c); Stranded people requires ‘Relief’. People should be housed in ‘Relief’ camps. CM would have held a review of the ‘Relief’ and rehabilitation work. Nonchalance *noun+ means ‘The state of being nonchalant; calm behavior that suggests you are not interested or do not care; calmness; equanimity; coolness;’. Succor *noun+ means ‘assistance and support in times of hardships and distress’. Deluge [noun] means ‘a severe flood’; Torrent *noun+ means ‘a severe flood’; Among the given options, ‘succor’ has a meaning very close to the meaning of ‘relief’. Hence, ‘Succor’ is the correct answer and option (c) is the correct answer. ",
		"Ans.162. (d); The last two sentences give the hint for the word which would fill the blank. ‘Extreme restraint was exercised, and opportunity was given to the militants to surrender. The four surrendered’. The highlighted sentences suggest that the militants weren’t killed or eliminated because extreme restraint was exercised, and the militants surrendered. Zap *verb+ means ‘go quickly’; Spawn *verb+ ‘(of a fish, frog, mollusk, crustacean, etc) release or deposit eggs; produce (offspring)’; The words ‘zapped’ and ‘spawned’ are irrelevant to the context of the sentences. It makes more sense that the surrendered militants were arrested. Hence, option (d) is the correct answer. ",
		"Ans.163. (b); Posit *verb+ means ‘to put forward as a fact or as a basis for argument’. The meaning of the word is irrelevant in the context of the given blanks. Similarly, the meaning of the words ‘belonged’, ’imprinted’ and ‘altered’ is irrelevant in the context of the given blanks. The Teen Murti Complex should be ‘attributed’ to Nehru Ji. The meaning of the word ‘dedicated’ is closer to the meaning of the word ‘attributed’. Hence, option (b) is the correct answer. ",
		"Ans.164. (e); Succor *noun+ means ‘assistance and support in times of hardships and distress’; Travesty *noun+ means ‘something that fails to represent the values and qualities that it is intended to represent, in a way that is shocking or offensive’; Equanimity *noun+ means ‘calmness and composure, especially in a difficult situation’; Deluge *noun+ means ‘a severe flood’; The words succor, travesty, equanimity and deluge are irrelevant in the context of the blanks. There is something called ‘rights of humans, rights of individuals, and rights of under-privileged; The word ‘rights’ correctly fits the blank. Hence, option (e) is the correct answer. ",
		"Ans.165. (a); Only the option (a) ‘herd’, upon filling the blanks, satisfy the contextual and grammatical requirements of the blanks. Hence, Option (a) is the correct answer. herd *noun+ means ‘a large group of animals, especially hoofed mammals, that live together or are kept together as livestock’; Pronouncement [noun] means ‘a formal or authoritative announcement or declaration’; Army *noun+ means ‘a group of soldiers’; Fleet *noun+ means ‘a group of ships’; Swarm *noun+ means ‘a large group of flying insects’; ",
		"Ans.166. (d); All three words (I), (II) and (III) are befitting to the given blanks as they give the similar meaning in all three cases to make the sentences meaningful. All three words 'impede', 'thwart' and 'inhibit' describe the same meaning 'prevent'. Hence option (d) is the correct choice. Impede means delay or prevent (someone or something) by obstructing them; hinder. Thwart means prevent (someone) from accomplishing something. Inhibit means hinder, restrain, or prevent (an action or process). Facilitate means make (an action or process) easy or easier. ",
		"Ans.167. (e); All the given words can be used in the provided blanks as they all give the similar meaning to the three sentences making them meaningful. Hence option (e) is the correct choice. Targeted means aimed or directed (something). Intended means designed or destined something for a particular purpose. ",
		"Ans.168. (a); Among the given choices, only the second word gives a contextual meaning to all the three sentences. Other words are not suitable in the context of adding meaning to the sentence. Hence option (a) is the correct choice. Repository means a person or thing regarded as a store of information or in which a particular quality may be found. Shade means a position of relative inferiority or obscurity. Dungeon means a strong underground prison cell, especially in a castle. ",
		"Ans.169. (b); Both the first and the second words can be used in the provided blanks to make them meaningful. Both the words give the similar meaning to the sentences. Hence option (b) is the correct choice. Persistent means continuing to exist or occur over a prolonged period. Lingering means lasting for a long time or slow to end. Intermittent means occurring at irregular intervals; not continuous or steady. Yielding means (of a person) complying with the requests or desires of others. ",
		"Ans.170. (e); All the four words are correct enough to fit into the provided blanks and thus adding the similar meaning in all the cases. All the four words mean the same. Hence option (e) is the correct choice. Emphatic means expressing something forcibly and clearly. Phenomenal means remarkable or exceptional, especially exceptionally good. Resounding means unmistakable; emphatic. Massive means large and heavy or solid. ",
		"Ans.171. (c); ‘expediency, opportunism’ is the pair of words that fits in the two sentences to make both the sentences grammatically and contextually complete. Expediency means the quality of being convenient and practical despite possibly being improper or immoral; convenience. Opportunism means the taking of opportunities as and when they arise, regardless of planning or principle. Here, the first sentence talks about persistence of alliance between PDP and BJP, such alliances persists because of political expediency. Hence, option (c) is the most appropriate choice. Infeasibility means not feasible; impracticable. Impracticality means not practical; not wise to put into or keep in practice or effect. Unwisdom means lack of wisdom. Dilemma means a situation in which a difficult choice has to be made between two or more alternatives, especially ones that are equally undesirable. ",
		"Ans.172. (e); ‘reluctance, noteworthy’ is the pair of words that fits in the two sentences to make both the sentences grammatically and contextually complete. Reluctance means unwillingness or disinclination to do something. Noteworthy means worth paying attention to; significant. Hence, option (e) is the most appropriate choice. Willingness means the quality or state of being prepared to do something; readiness. Astonishing means extremely surprising or impressive; amazing. Prosaic means having or using the style or diction of prose as opposed to poetry; lacking imaginativeness or originality. Suspicion means a feeling or thought that something is possible, likely, or true. ",
		"Ans.173. (b); ‘availed, widespread’ is the pair of words that fits in the two sentences to make both the sentences grammatically and contextually complete. Availed means use or take advantage of (an opportunity or available resource); help or benefit Widespread means found or distributed over a large area or number of people. In the first sentence ‘availed’ means taken or obtained and in the second sentence it means benefited. Hence, option (b) is the most appropriate choice. Compelled means forced or obliged (someone) to do something. Hindered means make it difficult for (someone) to do something or for (something) to happen. Restrained means kept under control. Bestowed means confer or present (an honour, right, or gift). Circumscribed means restrict (something) within limits. ",
		"Ans.174. (d); ‘trauma, discourage’ is the pair of words that fits in the two sentences to make both the sentences grammatically and contextually complete. Trauma means a deeply distressing or disturbing experience. Dissuade means persuade (someone) not to take a particular course of action. Hence, option (d) is the most appropriate choice. Equanimity means calmness and composure, especially in a difficult situation. Animate means give inspiration, encouragement, or renewed vigour to. Complacence means a feeling of smug or uncritical satisfaction with oneself or one's achievements. Distress means extreme anxiety, sorrow, or pain. Contentment means a state of happiness and satisfaction. Galvanize means shock or excite (someone) into taking action. Alleviation means the action or process of making suffering, deficiency, or a problem less severe. Invigorate means give strength or energy to. ",
		"Ans.175. (c); ‘established, sustaining’ is the pair of words that fits in the two sentences to make both the sentences grammatically and contextually complete. Established means having existed or done something for a long time and therefore recognized and generally accepted. Sustaining means strengthening or supporting physically or mentally Hence, option (c) is the most appropriate choice. Confuted means prove (a person or an assertion or accusation) to be wrong. Embedded means fixed (an object) firmly and deeply in a surrounding mass Repudiating means refusing to accept; rejecting. Authenticated means proved or showed (something) to be true, genuine, or valid ",
		"Ans.176. (b); The most suitable phrase to fill the blank is ‘hold up’ which means to remain strong or vigorous. All the other phrases fail to provide the appropriate context to the sentence. Hence, option (b) becomes the most viable answer choice. Call off means to decide that a planned event will not happen Leave out means to not include or mention (someone or something) Blow up means explode Bring up means (chiefly of a ship) come to a stop. ",
		"Ans.177. (e); The most suitable phrase to fill the blank is ‘look over’ which means a quick inspection of something; a survey. All the other phrases fail to provide the appropriate context to the sentence. Hence, option (e) becomes the most viable answer choice. Turn up means be found, especially by chance, after being lost. Take down means a police raid or arrest. Make out means make progress; fare. Make up means invent a story, lie, or plan. ",
		"Ans.178. (d); The most suitable phrase to fill the blank is ‘run through’ which means to practise something so that it is correct for a performance or test. All the other phrases fail to provide the appropriate context to the sentence. Hence, option (d) becomes the most viable answer choice. put out means cause someone trouble or inconvenience. put up means stay temporarily in accommodation other than one's own home. Run-away means escape from a place, person, or situation. run into means collide with. ",
		"Ans.179. (a); The most suitable phrase to fill the blank is ‘work out’ which means to find the solution by thinking or talking about it. All the other phrases fail to provide the appropriate context to the sentence. Hence, option (a) becomes the most viable answer choice. warm up means prepare for physical exertion or a performance by exercising or practising gently beforehand. wake up means an instance of a person waking up or being woken up turn down means a rejection or refusal. take out means a bid (in a different suit) made in response to a bid or double by one's partner. ",
		"Ans.180. (c); The most suitable phrase to fill the blank is ‘get back to’ which means to return to someone or something. This phrase is often used to say that you will return with an answer to a question or a request at a later time. All the other phrases fail to provide the appropriate context to the sentence. Hence, option (c) becomes the most viable answer choice. get up means (of wind or the sea) become strong or agitated. get back at means take revenge on (someone). get along with means another way of saying get on. get around means deal successfully with (a problem). ",
		"Thanx For Joining!, Have a nice day! 😎✌️🔥"
		
		]


#end...


