#FILLERS PART 5

questions=[	 ["Fillers going to be start in 30 secs..."],


			 ["Q.121. Children are more ____________ than adults, it is _____________ their quickness in learning a new language. (a) Intelligent, disproved by (b) Adaptable, reflected in (c) Conservative, seen in (d) Susceptible, demonstrated in (e) Resourceful, proportionate to"],
			 ["Q.122. He is ______ to_____ any kind of work with due sincerity. (a) Fond, perform (b) Reluctant, entrust (c) Determined, undertake (d) Eager, avoid (e) Willing, ignore"],
			 ["Q.123. Spring is in the air, and it is _____________to shake off the wooliness and ______________ the coolness and elegance of Indian cottons. (a) Period, accept (b) Moment, welcome (c) Occasion, hold (d) Time, embrace (e) Stage, adopt"],
			 ["Q.124. In a changing and _____ unstructured business environment, creativity and innovation are being _____ demanded of executives. (a) Excessively, rapidly (b) Highly, extremely (c) Increasingly, moderately (d) Progressively, increasingly (e) Highly, speedily"],
			 ["Q.125. For some years past, French Government had been _______ divided and French Parliaments had been incoherent and ______. (a) Inarticulate, responsive (b) Unable, domineering (c) Weak, inchoate (d) Many, few (e) Vacillating, irresponsible"],
			 ["Q.126. I was initially a bit ______________ that my daughter did not take up the puzzle, though she was ______________ good at it. (a) Disappointed, quite (b) Depressed, clearly (c) Motivated, freely (d) Sad, perfectly (e) Impressed, wholly"],
			 ["Q.127. Scientific imagination in a specific intellectual power that is ___________ in every population that has learned to be ______ about the mechanisms governing the physical world. (a) Encouraged, wary (b) Evoked, self-deprecatory (c) Latent, curious (d) Growing, self-possessed (e) Language, diffident"],
			 ["Q.128. In diplomatic ______ the _____ sought by one government from another to the name of a proposed ambassador is known as an 'agreement’. (a) Dealing, understandings (b) Parlance, condition (c) Language, interpretation (d) Circles, permission (e) Channels, condition"],
			 ["Q.129. Camille Pissarro, eldest of France’s great impressionist ______ that included Monet, Manet, Rennoir and Degas was the movement’s_______ and its saint. (a) Cabal, dosen (b) Sodality, gadfly (c) Entity, defector (d) Hierarchy, patriarch (e) Brotherhood, demon"],
			 ["Q.130. Even as _____ machines free men from drudgery, they ____ displace men from jobs. (a) Automated, simultaneously (b) Robotlike, unwillingly (c) Animated, ineluctably (d) Accelerated, seemingly (e) Antiquate, understandably III. Three Fillers Directions (131-140): In each of the following sentences there are blank spaces. Below each sentence there are five set of words denoted by the numbers (a), (b), (c), (d) and (e). Find out which set of words can be filled up in the blanks in the sentence in the same sequence to make it grammatically correct."],
			 ["Q.131. The Supreme Court’s seven-judge constitution bench gave the _______ in this case while _______the validity of the Bihar ordinance which was re-promulgated seven times since 1989 by the state government to _______certain benefits on Sanskrit teachers. (a) award, inspecting, withdraw (b) charge, observing, annul (c) take, overlooking, abrogate (d) verdict, examining, confer (e) call, interrogating, rescind"],
			 ["Q.132. The Constituent Assembly debates leave no manner of doubt that the said power ought not to be exercised merely to _______a failure to muster support in the legislature. The satisfaction of the president at the time of the promulgation of an ordinance is within the _______of judicial review. The government will have to _______the Court about whether the satisfaction for repromulgation was based on some relevant material. (a) dodge, cognizance, tantalize (b) comply, misconception, quench (c) circumvent, purview, satisfy (d) elude, understanding, pique (e) confront, understanding, satiate"],
			 ["Q.133. The practice becomes unacceptable when it degenerates into an 'ordinance raj', where ordinances are _______brought before the legislature but are re-issued again and again, _______the spirit of the Constitution. The court’s verdict has to be seen as placing a vital check on what has until now been a power _______abused by the executive. (a) infrequently, rebelling, profusely (b) seldom, violating, rampantly (c) often, complying, sparsely (d) occasionally, consecrating, bridledly (e) sporadically, deferring, profusely"],
			 ["Q.134. The temptation to use the power vested in the President and the Governors under Articles 123 and 213 of the Constitution is generally a result of one of the following three reasons: _______to face the legislature on particular issues, fear of _______in the Upper House where the government may lack the required numbers, and the need to overcome an impasse in the legislature caused by repeated and willful _______by a vociferous section of the Opposition. (a) reticence, winning , dislocation (b) willingness, losing, disturbance (c) unwillingness, trouncing, calmness (d) eagerness, overthrown, disturbance (e) reluctance, defeat, disruption"],
			 ["Q.135. Strong words are no substitute for action, however, and the strategic partnership that India _______with the UAE must be based on clarity and concrete measures. This should include a crackdown on the shadowy businesses owned by Dawood Ibrahim as well as more steps to ________terror financing of the Taliban and groups in Pakistan and Afghanistan; such money is often routed through ________remittances from the UAE. (a) anticipate, release, emigrant (b) envisions, curb, expatriate (c) ignore, constraint, repatriate (d) envisage, latitude, deportee (e) conceive, constraint, indigenous"],
			 ["Q.136. Amidst the rising pile of non-performing assets in governmentowned banks, willful defaulters were said to be responsible for around 77,000 crore of bad debts by last July, but the Kingfisher baron has emerged as the poster boy of the problem. Therefore the flurry of action on his bad loans, however belated, could help counter perceptions of a ____approach towards the well-heeled. Breaking the bankerborrower nexus is just as critical for _______public money as is acting against corrupt administrators, but a timely and transparent system is needed to _______that bankers don’t turn wary of extending credit at the slightest hint of risk. (a) passive, safeguarding, ensure (b) insurgent , armoring, enfeeble (c) acquiescent, attacking, assure (d) unresistant , assaulting, assure (e) contrary, protecting, secure"],
			 ["Q.137. It takes singular skill and acertain ruthlessness, however, to make capital of the smallest advantages, and Federer and Serena, and to a marginally_________ extent Nadal and Venus, did precisely that. Federer, who missed six months last year with an injury, knew he could not allow Nadal time and space. With his opponent looking in excellent physical condition, Federer could not ________to be drawn into long, bruising rallies; he had to dictate the ________of play. (a) minute, reject, pace (b) auxiliary, sustain, chance (c) larger, manage, pace (d) lower, refuse, cadence (e) lesser, afford, tempo"],
			 ["Q.138. The collision of the Hubli-Bengaluru City Hampi Express with a goods train that left 25 people dead, for instance, was caused by _________of staff. The Kakodkarcommittee on railway safety found that out of 441 derailments it_________, only about 15% were the result of__________, while the majority were caused by factors completely under the control of the railway administration. (a) compliance, examined, vandalism (b) failure, analysed, sabotage (c) fault, agglomerated , disruption (d) carelessness, inspected, loyalty (e) achievement, evaluated, destruction"],
			 ["Q.139. India’s Railways serves the __________function of providing travel access to millions, and, as Mahatma Gandhi wrote in his article 'Third Class in Indian Railways’, have the _________of making it equitable and comfortable. It must also be safe. The Railway Ministry is ___________a major safety initiative, the Rashtriya Rail SanrakshaKosh, with a non-lapsable corpus of Rs.1,19,183 crore. (a) lethargic, obligatory, chasing (b) important, liability, shunning (c) vital, responsibility, pursuing (d) essential, irresonsiblility, following (e) indispensable, duty, eschewing"],
			 ["Q.140. While bilateral ties have been _________for decades, the defence and security partnership is clearly the new driver for ties between the two governments; the signing of the strategic partnership agreement was the highlight of the UAE leader’s visit. The _________of this partnership are now being set: joint military exercises, joint manufacturing and purchase of equipment and spare parts from India, as well as ________on fighting terror. (a) strong, outline, division (b) frail, profile, collaboration (c) vigorous, configuration, contention (d) sturdy, affection, synergy (e) robust, contours, cooperation"],
			 ["Q.141. Despite __________interest in the putative benefits of free trade and globalization in the West amid a ____________in economic nationalist leaders, demand for trade liberalization persists in the Asia-Pacific. Though there are no other multilateral arrangements __________to the complexity of nontariff provisions included in the TPP, two arrangements are notable for at least including a comparably large collection of economies. (a) declining, disappear, ambitious (b) fading, rise, apathetic (c) burgeoning, deteriorate, yearning (d) waning, surge, aspiring (e) flourishing, rush, desiring"],
			 ["Q.142. It is said in the budget that ____________ changes would be made in the law to bring down prices of essential drugs and health equipments. Production of generic drugs would be___________. Budget talks about opening new AIIMS also. However, these provisions are not sufficient. People lose their savings and whatever _________they have for treatment of their near and dear ones. (a) Dispensable, stimulated, money (b) Imperative, dissuaded, possessions (c) Requisite, encouraged, assets (d) Superfluous, incited, capital (e) Essential, deterred, property"],
			 ["Q.143. Higher oil price-led inflation will bring back into focus the high excise duties on petroleum products that have __________the Centre’s tax kitty over the past couple of years. Those duties were raised when prices were low to __________consumers from an upward price shock, the government had argued. Cutting those duties will upset _________calculations, but leaving them untouched will impose its own costs. (a) Raised, assault, profit (b) Aided, defend, expense (c) Advanced, annihilate, outlay (d) Hindered, guard, return (e) Boosted, protect, revenue"],
			 ["Q.144. In India, we have been in the process of encouraging FDI not only in the development sectors, but in retail segment as well in order to __________foreign funds with incidental advantages of technology transfer, job opportunities and __________to domestic firms and consumers. But since education is not a tradable commodity, the __________of FDI in the higher educational sector call for reflection. (a) Abate, favors, connotations (b) Enhance, benefits, implications (c) Increase, supports, exclude (d) Dwindle, avails, indications (e) Improve, detriments, significance"],
			 ["Q.145. Many of the renowned off-shore universities are willing to invest in campuses abroad, and, in practice, it is hard to __________the standards of the home country in some other country. Other related problems are: returns from the investment made in _________ and running of campuses, non-repatriation of profits as mentioned, the regulatory mechanism of the host country in regard to the fee-structure, faculty salaries, curriculum to be offered, and issues _________to research and intellectual property rights etc. (a) Replicate, establishing, pertaining (b) Copy, nullify, applying (c) Concurring, determining, existing (d) Duplicate, annihilate, concerning (e) Avowal, setting up, associating"],
			 ["Q.146. Mr. Trump could either fight back or make peace. Two days after Mr. Flynn’s resignation, he has signaled both. He attacked the intelligence agencies on Twitter on Wednesday, while the White House_________ that the promised détente with Russia was over. But Mr. Flynn has set in motion a process that is unlikely to be controlled by a seemingly __________ administration like Mr. Trump’s. With chaos engulfing his government, Mr. Trump will be forced to__________. (a) Imply, efficient, submit (b) Denoted, ability, acquiesces (c) Abrogated, ineptitude, comply (d) Indicated, incompetent, conform (e) Refute, Inadequacy, agree"],
			 ["Q.147. It has often chosen to play _______ moral guardian rather than ________ films by content and letting audiences make ________ decisions. (a) smile, tangling, authentic (b) staring , distorting, genuine (c) glowering , labeling, informed (d) pleasing, confusing, enlightened (e) orthodox, producing, sophisticated"],
			 ["Q.148. At home, while security forces deserve ________ for limiting the Pathankot air base attack, many questions need to be _________ about the state of ________ along the Punjab-Pakistan border. (a) condemnation, replied, peril (b) praise, acknowledged, security (c) blame, replied ,danger (d) censure, answered, insecurity (e) credit, rebutted, chaos"],
			 ["Q.149. Its surprise result in Bihar where it _______ itself to regional players and ______ a windfall holds out a _________________. (a) begrimed, doubted , stencil (b) dirty, be surprised, stencil (c) sublimated , gained, template (d) polluted, be amazed, prototype (e) rewired, produced, cynosure."],
			 ["Q.150. Consider innovations like the India Stack which _______ Aadhaar authentication, e-KYC, esign, Digital Locker and UPI_______ mobile payments to ___________ cashless, paperless and presence-less transactions. (a) part, improbable, impart (b) dissolve, impractical, pledge (c) detach, disconnect, yield (d) combines , interoperable, provide (e) consists, easy, issue "],

			 ["Now Over!!"]
 
 ]
 
 #FILLERS  solution PART 5

sol=[	"Lets Start!",


		"Ans.121. (b); ‘Adaptable, reflected in’ is the correct use. Adaptable: Able to adjust to new conditions. Reflected in: Represent (something) in an appropriate way. ",
		"Ans.122. (c); ‘Determined, undertake’ is the correct use. Determined: To decide firmly Undertake: To Commit oneself to and begin (an enterprise or responsibility) ",
		"Ans.123. (d); ‘Time, embrace’ is the correct use. Embrace: An act of accepting something willingly or enthusiastically. ",
		"Ans.124. (d); ‘Progressively, increasingly’ is the correct use. Progressively: To move towards better conditions. ",
		"Ans.125. (e); ‘Vacillating, irresponsible’ is the correct use. Vacillating: To be indecisive. Irresponsible: Not showing a proper sense of responsibility. ",
		"Ans.126. (a); ‘Disappointed, quite’ is the correct use. Disappointed: Saddened Quite: To a certain or fairly significant extent ",
		"Ans.127. (c); ‘Latent, curious’ is the correct use. Latent: Existing but not yet developed Curious: To be eager to know or learn something. ",
		"Ans.128. (b); ‘Parlance, condition’ is the correct use. Parlance: A particular way of speaking or using words, Condition: A situation that must exist before something else is possible or permitted. ",
		"Ans.129. (d); ‘Hierarchy, patriarch’ is the correct use. Hierarchy: a system in which members of an organization or society are ranked according to relative status or authority. Patriarch: the male head of a family or tribe. ",
		"Ans.130. (b); ‘Robotlike, unwillingly’ is the correct use. Robotlike: Resembling a robot. Unwillingly: Not ready, eager, or prepared to do something. III. Three Fillers ",
		"Ans.131. (d); Verdict- a decision on an issue of fact in a civil or criminal case or an inquest. Examining- inspect (someone or something) thoroughly in order to determine their nature or condition. Confer- grant (a title, degree, benefit, or right). ",
		"Ans.132. (c); Circumvent- deceive; outwit. Purview- the scope of the influence or concerns of something. Satisfy- meet the expectations, needs, or desires of (someone). ",
		"Ans.133. (b); Seldom- not often; rarely. Violating- break or fail to comply with (a rule or formal agreement). Rampantly- Extending unchecked; unrestrained ",
		"Ans.134. (e); Reluctance- unwillingness or disinclination to do something. Defeat- reject or block (a motion or proposal). Disruption- disturbance or problems which interrupt an event, activity, or process. ",
		"Ans.135. (b); Envisions- imagine as a future possibility; visualize. Curb- a check or restraint on something. Expatriate- send (a person or money) abroad. ",
		"Ans.136. (a); Passive- accepting or allowing what happens or what others do, without active response or resistance. Safeguarding- protect from harm or damage with an appropriate measure. Ensure- make certain that (something) will occur or be the case. ",
		"Ans.137. (e); Tempo means the rate or speed of motion or activity. ",
		"Ans.138. (b); Sabotage means deliberately destroy, damage, or obstruct (something), especially for political or military advantage. ",
		"Ans.139. (c); Pursuing means following or chasing (someone or something). ",
		"Ans.140. (e); Contour means an outline representing or bounding the shape or form of something.Robust means strong and healthy; vigorous. ",
		"Ans.141. (d); Waning means (of a state or feeling) decreasing in vigour or extent; becoming weaker. ",
		"Ans.142. (c); Option (c) is true. Requisite means which is necessary or required. Superfluous means redundant, surplus ",
		"Ans.143. (e); Option (e) is true. Annihilate means to destroy. ",
		"Ans.144. (b); Option (b) is true. Detriment means any harm or damage. Abate means to diminish. ",
		"Ans.145. (a); Option (a) is true. Pertaining means to be appropriate ",
		"Ans.146. (d); Option (d) is true. Refute means disapprove. Abrogate means to evade. ",
		"Ans.147. (c); ‘glowering , labeling, informed’ fits the blank perfectly. Glowering means have an angry or sullen look on one’s face; scowl. ",
		"Ans.148. (b); 'praise, acknowledged, security', fits the blanks most appropriately and is the correct choice. ",
		"Ans.149. (c); 'sublimated , gained, template', fits the blanks most appropriately. Sublimated means (in psychoanalytic theory) divert or modify (an instinctual impulse) into a culturally higher or socially more acceptable activity. ",
		"Ans.150. (d); 'combines , interoperable, provide', fits the blanks most perfectly. Interoperable means (of computer systems or software) able to exchange and make use of information. ",
		"Thanx For Joining!, Have a nice day! 😎✌️🔥"
]


#end...
