questions = [
							[ "Quiz ADJECTIVE: will start in 30 secs. " ],
							
							["1. (a) The two first to arrive/(b) were the lucky/(c) recipients of /(d) the scholarship./(e) No error"  ],
							["2. (a) Of the millions of stars/(b) in the galaxy,/(c) how much /(d) support life?/(e) No error"  ],
							["3. (a) A few chapter/(b) of this book/(c) are important from/(d) examination point of view. /(e) No error"  ],
							["4. (a) I like singing/(b) more than/(c) to dance/(d) games./(e) No error"  ],
							["5. (a) There is not/(b) many traffic/(c) along the street/(d) where they live./(e) No error"  ],
							["6. (a) The food inspector arrived and discovered/(b) a large number of /(c) hoarded rice/(d) in his shop./ (e) No error"  ],
							["7. (a) According to me/(b) Rajeev is senior /(c) from any other accountant/ (d) of his office/(e) No error"  ],
							["8. (a) Shivam is/(b) the tallest and/(c) smarter student/(d) of his class./ (e) No error"  ],
							["9. (a) The credit unions are the co-operative/(b) financial institutions similarly to a bank/(c) but unlike banks the credit unions/(d) are owned by the members. ./ (e) No error"  ],
							["10 (a) Diamond is/(b) harder than/ (c) any other/(d) metal /(e) No error"  ],
							["11. (a) Sameer ran to the/(b) nearing confectionary store to/(c) buy biscuits as his parents/(d) were expecting guests./(e) No error"  ],
							["12. (a) It was thought/ (b) that he’d committed the crime/(c) but there wasn’t /(d) sufficiently evidence to convict him./(e) No error"  ],
							["13. (a) Although his speech/(b) was not very clearly/(c) everyone understood/(d) the underlying meaning./(e) No error"  ],
							["14. (a) He is the most/(b) intelligent and also/(c) the very talented/(d) student of the college./(e) No error"  ],
							["15. (a) A Ten-miles walk/(b) is really a/ (c) herculean task for/(d) someone of his age./(e) No error"  ],
							["16. (a) The deplorably/(b) events of/(c) 1947 were /(d)reenacted in 1983. /(e) No error"  ],
							["17. (a) Fingers bowl is typically served/(b) before the dessert course/(c) arriving with the dessert plate and with/(d) a linen doily between plate and bowl./(e) No error"  ],
							["18. (a) The number of /(b) cases of robbery has /(c) risen this year by /(d) as many as 30%/ (e) No error"  ],
							["19. (a) Ten thousand of candidates/ (b) attended the conference/(c) held in the/(d) Head branch of Career Power./(e) No error"  ],
							["20. (a) These sort of men/(b) achieve their goals by hook or by crook/(c) so they do not/(d) deserve any applause. /(e) No error"  ],
							["21. (a) Can you tell me /(b) how many/(c) eggs and milk/(d) he has brought/(e) No error"  ],
							["22. (a) Ashish bought/(b) golden long round earrings/(c) for his mother/ (d) on her birthday./ (e) No error"  ],
							["23. (a) The police investigation/(b) revealed that the murderer/(c) had used a sharp long knife/(d) for killing Mr. Kumar./ (e) No error"  ],
							["24. (a) Sanjay is more industrious/(b) and smarter than/(c) any other player/(d) of his team./ (e) No error"  ],
							["25. (a) My house/(b) is further/(c) than/(d) his house./(e) No error"  ],
							["26. (a) This book is undoubtedly/(b) preferable than/ (c) that and its content and concepts /(d) are also comparatively good./(e) No error"  ],
							["27. (a) Do you know that /(b) the latest/(c) boy in the row/(d) is my brother./(e) No error"  ],
							["28. (a) Everybody knows/(b) that Ravina is/(c) the most unique/(d) dancer of this school./(e) No error"  ],
							["29. (a) He does not have/(b) some time to prepare /(c) for the exam so he is/(d) anxious./(e) No error"  ],
							["30 (a) Suman is as older as/(b) her husband yet/(c) she looks younger/ (d) than him./(e)No error"  ],
							["31. (a) Although, Sameer and Vishal/(b) are tall but /(c) Vishal is comparatively taller/(d) than Sameer./(e) No error"  ],
							["32. (a) Sam is as smart/(b) if not /(c) smarter than/(d) they/(e) No error"  ],
							["33. (a) Govind felt/(b) sadly to learn that/(c) his brother had/(d) failed the UPSC exam./(e) No error"  ],
							["34. (a) She is comparatively/(b)stronger/(c)in Mathematics/(d) than in any other subject./(e) No error"  ],
							["35. (a) Many a/(b) girls are/(c) present/(d) today/(e) No error"  ],
							["36. (a) The dishonest/(b) are/(c) panelised /(d) sooner or later/(e) No error"  ],
							[" 37. (a) My all /(b) relatives will come/(c) tomorrow to attend/ (d)my sister’s wedding. /(e) No error"  ],
							["38. (a) Ravish is stronger/(b) enough to lift/(c) these boxes/(d) on his own,/(e) No error"  ],
							["39. (a) Mahabharata is larger/ (b) than/(c) all the mythologies/(d) of Hindus/(e) No error"  ],
							["40 (a) She offered/(b) me a /(c) steamed cup/(d) of coffee/(e) No error"  ],
							["41. (a) She ran so fastly /(b) that she reached/(c) the station in/(d) just two minutes./(e) No error"  ],
							["42. (a) She speaks/ (b) so loudly that/ (c) even a deaf/ (d) can hear her voice./ (e) No error"  ],
							["43. (a) I am /(b) more happier/(c) here than/I was in the UK./No error"  ],
							["44. (a) This might be/(b) the more difficult/(c) task he would/(d) ever perform./(e) No error"  ],
							["45. (a) The ratings/(b) of this movie/(c) are higher than/(d) that of any movie/(e) No error"  ],
							["46. (a) In the market/(b) were the more/(c) popular encyclopedias and science journals/(d) for the students./(e) No error"  ],
							["47. (a) In his adulthood/ (b) a person is /(c) likely to get/(d) more wise day by day./(e) No error"  ],
							["48. (a) Her impudent behavior/(b) was completely/(c) inappropriate for such/(d) a formal occasion./ (e) No error"  ],
							["49. (a) A robot/ (b) is thousand times/(c) more efficient/(d) than a man./ (e) No error"  ],
							["50. (a) It very often/(b) happens that a /(c)man who talks /(d) most does little./(e) No error"  ],


							[ "Now OVER!!! Just rate us!"]
							]
							
							
							
							
							
							
							
							
sol =	[	"Lets Start!",


			"1. (a); 'The first two' should be used in place of 'The two first'. Since, 'ordinals' are always used before 	'cardinals'",
			"2. (c); 'Many' Should be used in place of 'much'. Since, 'many' is used for 'countable' nouns and 'much' is used for 'uncountable' nouns and 'stars' are countableNote: Stars are countless, not uncountable",
			"3. (a); 'chapters' should be used in place of 'chapter'. Since, 'a few' is always followed by a plural noun",
			"4. (c); 'to dance' should be replaced with 'dancing'. Since, singing is a gerund and it should be compared with a gerund only",
			"5. (b); 'much' should be used in place of 'many' since, 'Traffic' is an uncountable noun",
			"6. (b); 'Rice' is an uncountable noun. Hence, 'quantity' should be used in place of 'numbers'",
			"7. (c); 'Senior' is always followed by 'to' Hence, 'to' should be used in place of 'from'",
			" 8. (c); 'Smartest' should be used in place of 'smarter', since, 'Adjectives' of same degree are used for a single noun of pronoun",
			"9. (b); 'Similar' should be used in place of 'Similarly'. Since, 'similar' is an adjective which should be used to quality a noun",
			"10. (c); 'Any metal' should be used in place of 'any other metal'. Since, diamond is not a metalNote: If something is compared with all the others of the same class, then 'all/any other' is used to exclude the former from the whole class. Whereas, if something is compared with a completely different class, then 'any' + 'name of class' is used For eg:- Gold is costlier than 'any other' metal. Here, 'any other' separates gold from the whole class of metals Diamond is harder than any metal. Here, 'any 'metal' is used since 'Diamond' is not a metal",
			"11. (b); 'nearby' should be used in place of 'nearing' since 'nearing' is not an adjective. Hence, an adjective, 'nearby' should be used to qualify 'grocery store'", 
			"12. (d); 'sufficient' (an adjective) should be used in place of 'sufficiently' can adverb) to qualify 'evidence' (a noun)",
			"13. (b); 'Clear' can 'adjective' should be used in place of 'clearly (an adverb) to qualify 'voice' (a noun)",
			"14. (c); 'Most' should be used in place of 'very'. For explanation refer to question-8",
			"15. (a); 'Ten-mile walk' should be used place of 'Ten-miles walk'. Since, Hyphenated adjectives are always used in singular form",
			"16. (a); 'deplorable' should be used in place of 'deplorably'",
			"17. (a); 'Finger bowl' should be used in place of 'fingers bowl', Since, here 'finger's is used as an adjective and if a noun is used as an adjective, it should be in singular form",
			"18. (d); 'as much as' should be used in place of 'as many as'. Since, when a plural number is used as a singular unit, 'much' is used",
			"19. (a); 'of' should not be used here. Since, 'of' does not follow a definite numeral adjective",
			"20. (a); 'These sorts of men' should be used in place of 'These sort of men'Since, words like 'sort, 'kind', etc. are used in plural form, when they are used as an adjective to qualify a plural noun",
			"21. (b); 'How much' should be used in place of 'How many. Since, oil is an uncountable noun, therefore, 'much' should be used",
			"22. (b); 'Long round golden earrings' should be used in place of 'golden long round earrings' for explanation refer to 13 of correct usage of adjectives",
			"23. (c); 'Long sharp knife' is the correct usage as per rule 13 of 'correct usage of adjectives.'",
			" 24. (e); No error",
			"25. (b); 'farther' should be used in place of 'further' Refer to rule 12 (i) for explanation",
			"26. (b); 'to' should be used in place of 'than' Since 'preferable' is followed by 'to' ",
			"27. (b); 'last' should be used in place of 'latest' refer to rule 12 (ii) for explanation",
			"28. (c); 'a unique' should be used in place of the unique'. Since, 'Unique' is not used in superlative or comparative degree",
			"29. (b); 'any' should be used in place of 'some'. Since, 'any' is used in negative sentences and 'some' is used in positive sentences",
			"30. (a); 'older' should be used in place of 'old'. Since 'comparative + and + comparative' is used to show a gradual change",
			"31. (c); 'tall' should be used in place of 'taller' since the word 'Comparatively' is not followed by a comparative degree",
			"32. (a); 'as smart as as' is the correct usage",
			"33. (b); 'sad' should be used in place of 'sadly'. Since, an adjective (here, sad) is used with verbs of sensation",
			"34. (b); 'Strong' should be used in place of 'stronger'. See question 31 for explanation",
			"35. (b); 'girl is' should be in place of 'girls are' since 'many a' is followed by singular noun and singular verb",
			"36. (b); 'are' should be used in place of 'is' since an adjective becomes a plural common noun whenever 'the' precedes it",
			"37. (a); 'All my' should be used in place of my all",
			"38. (a); 'Strong' should be used in place of 'stronger' since 'enough' is always preceded by a positive degree",
			"39. (c); 'All other mythologies' should be used in place of 'all the mythologies'. For explanation refer to question – 10",
			"40. (e); No error",
			"41. (a); 'fast' should be used in place of 'fastly'",
			"42. (b); 'loud' should be used in place of 'loudly '. Since, an adjective of positive degree is used in between So _______that",
			"43. (b); 'more' should not be used here. Since, two comparative degrees are not used together",
			"44. (b); 'most' should be used in place of 'more'. Since, the 'task' is compared will all the other tasks. Hence, superlative degree should be used",
			"45. (d); 'Any other movie' should be used in place of 'Any movie. For explanation refer to question – 10",
			"46. (b); 'most' should be used in place of 'more'",
			"47. (d); 'wiser' should be used in place of 'more wise'. Since 'weaker' is the comparative degree of 'weak'",
			"48. (e); No error",
			"49. (c); 'efficient' should be used in place of 'more efficient' Since, comparative degree not used with 'times'",
			"50. (d); 'much' should be used in place of 'most' since 'work' is uncountable" , 
			
			"Thnx for Joining"
			]

