questions =	 [
				[ " Quiz: ADVERB and Voice will start in 30 secs. " ],
							
				["1. (a) Her speech was / (b) not clearly but / (c)we understood / (d) the underlying meaning. / (e) No error" ],
				[" 2. (a) Teena worked / (b) very hardly / (c) as she wanted / (d) to be surgeon/ (e) No error" ],
				[" 3. (a) You have / (b) acted nobler / (c) than / (d) all of us. / (e) No error" ],
				["4. (a) When she received / (b) the good news, she ran / (c) straightly to / (d) call up her parents. / (e) No error" ],
				["5. (a) Rahul could not scarcely / (b) conceal his / (c) happiness at/ (d) my resignation. / (e) No error" ],
				["6. (a) We seldom or ever / (b) go out these days / (c) because it is too/ (d) hot now-a-days. / (e) No error" ],
				[" 7. (a) The State Government / (b) appointed him as / (c) officer-in-charge. / last month. (d) / " ],
				[" (e) 8. (a) Great leaders tried / (b) to eradicate social / (c) evil practices / (d) with tooth and nail. / (e) No error" ],
				[" 9. (a) She is either / (b) dumb or / (c) deaf, if / (d) not both. / (e) No error" ],
				[" 10. (a) She does her / (b) work good / (c) as she is / (d) a trained nurse. / (e) No error" ],
				[" 11. (a) Outright rejection / (b) of my plea / (c) disappointed me. /(d) a lot. / (e) No error" ],
				[" 12. (a) My father / (b) is very quicker / (c) than I / (d) at Chess. / (e) No error" ],
				[" 13. (a) I / (b) see him often / (c) at the / (d) bus terminal. / (e) No error" ],
				[" 14. (a) I refused to consider / (b) him as an honest boy / (c) as he had / (d) cheated many people. / (e) No error" ],
				[" 15. (a) I have / (b) never seen a / (c) coward man. / (d) like Rohan. / (e) No error" ],
				["  16. (a) A man of fifty / (b) cannot be / (c) called / (d) as young. / (e) No error" ],
				["17. (a) He is enough tall / (b) to be selected / (c) as Sub Inspector / (d) In Delhi Police. / (e) No error" ],
				[" 18. (a) I did not know hardly / (b) anyone in the college / (c) and so I felt lonely / (d) all the time. / (e) No error" ],
				["19. (a) I never remember / (b) to have met a / (c) more intelligent / (d) man in my life. / (e) No error" ],
				["20. (a) All the pupils / (b) stood up respectively / (c) as the teacher / (d) entered the room / (e) No error" ],
				["21. (a) Mangoes taste / (b) more sweetly than / (c) any other fruit / (d) of this world. / (e) No error" ],
				[" 22. (a) Never in the history / (b) there has been / (c) as shrewd a / (d) mentor as Chanakya. / (e) No error" ],
				["23. (a) She had barely / (b) nothing to wear / (c) when she came / (d) to me for help. / (e) No error" ],
				["24. (a) Vijay could not / (b) scarely conceal his / (c) happiness at / (d) my resignation. / (e) No error" ],
				["25. (a) It rained / (b) like cats and dogs / (c) throughout / (d) the night. / (e) No error" ],
				[" 26. (a) Though he was brave, / (b) he could not face / (c) the ups and downs / (d) of the manly. / (e)", "1 (A)", "2 (B)", "3 (C)","4 (D)","No error", "D" ],
				[" 27. (a) I am full / (b) of energy today / (c) because I soundly / (d) slept last night / (e) No error" ],
				[" 28. (a) When I read his biography, / (b) I hardly found something / (c) in his character that / (d) I could admire. / (e) No error" ],
				[" 29. (a) He is / (b) niggard and / (c) saves each / (d) every paise / (e) No error" ],
				["30. (a) Her speech was / (b) not clearly but / (c) we understood / (d) the underlying meaning. / (e) No error" ],
				[" 31. (a) We usual have / (b) a meeting of / (c) all department / (d) heads every Friday / (e) No error" ],
				[" 32. (a) Donations received / (b) by the Trust / (c) will be proper / (d) accounted for. / (e) No error" ],
				[" 33. (a) He admitted to / (b) me that had not / (c) adequate prepared / (d) for the test. / (e) No error" ],
				[" 34. (a) It was too cold for / (b) go out last evening / (c) so we all / (d) stayed at home. / (e) No error" ],
				[" 35. (a) The latest study by NASSCOM / (b) indicates possibly short / (c) of five lakh qualified / (d) engineers in the IT industry. / (e) No error" ],
				
				["Voice Started:--> 1. (a) The officers/(b) who were on inspection/(c) in this exam centre were discovered/(d) many discrepancies. /(e) ", "1 (A)", "2 (B)", "3 (C)","4 (D)","No error", "" ],
				["2. (a) The teacher asked/(b) the students whether they/(c) could tell the name of the man /(d) who had been invented electricity./(e) ", "1 (A)", "2 (B)", "3 (C)","4 (D)","No error", "" ],
				["3. (a) She held a gun/(b) in her hand which/(c) was totally hiding in the long cloak /(d) that she was wearing. /(e) ", "1 (A)", "2 (B)", "3 (C)","4 (D)","No error", "" ],
				["4. (a) I was surprise/(b) at her contemptuous behaviour/(c)as she was considered/(d) an obedient child/(e)", "1 (A)", "2 (B)", "3 (C)","4 (D)","No error", "" ],
				["5. (a) Had the police not/(b) reached there/(c)on time, the bank/(d) would have robbed./(e) ", "1 (A)", "2 (B)", "3 (C)","4 (D)","No error", "" ],
				["6. (a) The soldier seriously injured/(b) during the cross fire/(c) and was rushed/(d) to hospital/(e)", "1 (A)", "2 (B)", "3 (C)","4 (D)","No error", "" ],
				["7. (a) Police officers sent/(b) to the place of crime and /(c) every nook and corner/(d) was thoroughly checked./(e) ", "1 (A)", "2 (B)", "3 (C)","4 (D)","No error", "" ],
				["8. (a) When the police officer was shot dead/(b) people were run/(c) here and there/(d) to save themselves./(e) ", "1 (A)", "2 (B)", "3 (C)","4 (D)","No error", "" ],
				["9. (a) Mother's love/(b) cannot substituted/(c) by anything/(d) else in this world./(e) ", "1 (A)", "2 (B)", "3 (C)","4 (D)","No error", "" ],
				["10. (a) When the robber broke into/(b) the bank, the/(c) staff raised a hue and cry and the robber caught /(d) immediately by the people./ (e) ", "1 (A)", "2 (B)", "3 (C)","4 (D)","No error", "" ],
				["11. (a) The city/(b) was tore/(c)by earthquake/ (d) previous year./(e)", "1 (A)", "2 (B)", "3 (C)","4 (D)","No error", "" ],
				["12. (a) The taxi driver/(b) was accused the man/(c) for walking in/(d) the middle of the road./(e) ", "1 (A)", "2 (B)", "3 (C)","4 (D)","No error", "" ],
				["13. (a) Some passengers/(b) were flew/(c)to London on/ (d) the last trip./(e) ", "1 (A)", "2 (B)", "3 (C)","4 (D)","No error", "" ],
				["14. (a) By the time/(b) he arrived,/ (c) everybody had been/(d) left for the party./ (e) ", "1 (A)", "2 (B)", "3 (C)","4 (D)","No error", "" ],
				["15. (a) She was/ (b) extremely annoyed/(c) by/ (d) the ill behavior of the bank staff./(e) ", "1 (A)", "2 (B)", "3 (C)","4 (D)","No error", "" ],	
				
				[ "Now OVER!!! Just rate us!"]
							]
							
						

						
						
sol=							[	"Lets Start!",


									"1. (b); 'Speech (noun) will be qualified by an adjective 'clear'",
									"2. (b); 'Hard' must replace 'hardly' here",
									"3. (b); Use 'more nobly'. 'Nobler' is an adjective and here we need an adverb",
									"4. (c); 'Straight' is both adverb and adjective. 'Straightly' is a wrong word",
									"5. (a); Scarcely cannot be used with 'not'",
									"6. (a); 'Seldom' is followed either by 'if ever' or by 'or never' ",
									"7. (b); Remove 'as'. Appoint is not followed by 'as'",
									"8. (d); Remove 'with'",
									"9. (d); Change 'if not both' into 'if neither'",
									"10. (b); 'Good' is an adjective. Use adverb 'well' here",
									"11. (d); No error",
									"12. (b); 'Much' will come with 'quicker' (comparative degree)",
									"13. (b); 'Often' will come before the main verb 'see'",
									"14. (b); Remove 'as'. Since as does not follow consider",
									"15. (e); No error",
									"16. (d); Remove 'as'",
									"17. (a); 'Enough' comes after an 'adjective'. Put 'enough' after 'tall'",
									"18. (a); Hardly cannot take 'not' after it",
									"19. (a); 'Never' will come after 'remember'",
									"20. (b); Change 'respectively' to 'respectfully'",
									"21. (a); 'Taste' is a verb of sensation that takes an adjective and not an adverb. Change 'more sweetly' into 'sweeter'",
									"22. (b); Never (adverb) will be followed by a helping verb (has) first and then the subject",
									"23. (b); 'Barely' will not take 'nothing' after it. Change 'nothing' into 'anything'",
									"24. (a); Remove 'not'. Since, not is not used with scarely",
									"25. (b); Remove 'like'",
									"26. (d); Change 'manly' into 'manfully'. 'Manly' is adjective. It means 'brave /strong'",
									"27. (b); 'Seldom' is followed by 'never'",
									" 28. (b); 'Hardly' will come with 'anything'",
									"29. (b); Add 'a' before niggard",
									"30. (b); 'Speech' (noun) will be qualified by an adjective 'clear'",
									"31. (a); 'usually' is the right adverb ",
									"32. (c); 'properly' is the right adverb ",
									"33. (c); 'adequately' is the correct adverb to modify prepared ",
									"34. (a); 'Too' is followed 'To' ",
									"35. (b); 'Possible' is the correct adverb ",
									"Voice Ans--> 1. (c); 'were' should be removed from here. Since, past indefinite tense 'V2 ' is used in active voice",
									"2. (d); 'been' should not be used here. Since, the given sentence is in active voice hence, the structure 'had + been + v3 ' will not be used here",
									"3. (c); 'hidden' should be used in place of 'hiding'",
									"4. (a); 'surprised' should be use in place of 'surprise. Since the given sentence is in passive voice. Hence, 'V3 ' should be used",
									"5. (d); 'would have been' should be used in place of 'would have'. Since the given sentence is in passive voice. Hence, 'would + have + been' should be used",
									"6. (a); 'The soldier was seriously injured' should be used in place of 'The soldier seriously injured'. Since 'The soldier seriously injured' means that 'The soldier was involved in the act of injuring someone'",
									"7. (a); 'were sent' should be used in place of 'sent' ",
									"8. (b); 'were run' should be replaced with 'ran'. Since the given sentence is in active voice",
									"9. (b); 'be' should be added after 'cannot'. Since, in passive voice, the structure 'model + be + v3 ' is used",
									"10. (c); 'robber was caught' should be used in place of 'robber caught' Since 'robber caught' means 'robber was the doer of the action'",
									"11. (b); 'torn' should be used in place of 'tore'. Since, in passive voice, 'V3 ' is used after 'was/were",
									"12. (b); 'was' should not be used here. Since the sentence is not in passive voice",
									 "13. (b); 'flown' (v3 ) should be used in place of 'flew'. Since, the given sentence is in passive voice. Hence, V3  should be used",
									"14. (c); 'been' should be removed from the given sentence. Since, the given sentence is in active voice, Hence 'has/have/had + been' should not be used",
									"15. (c); 'at' should be used in place of 'by'. Since, we are 'annoyed at something' and 'annoyed with someone'",
									"Thnx for Joining"
									]

