    
	
questions =     [
					[ " Quiz-Articles will start in 30 secs. " ],
						
					["1. (a) It is only after/(b) the movie is over/ (c) that people realize/(d)how good or bad it was/ (e) No error"],
					["2. (a) Of the two/(b) cars, this/(c) is definitely/(d) better./(e) No error."],
					["3. (a) Rajeev is unfortunate enough/(b) to lose/(c) few friends he made/(d) during his stay at Delhi./(e) No error"],
					["4. (a) There were a number/(b) of pretty girls in the party/(c) but it was  Neelam/(d) who remained a   centre of attraction./ (e) Noerror."],
					["5. (a) I have been /(b) informed that/(c) Dr Sharma visits Mumbai/(d) the following week./(e) No error"],
					["6. (a) He is /(b)the best singer/(c) of the time but unfortunately/(d)least recognized /(e) No error"],
					["7. (a) Raju said that he felt ecstatic/(b) because a friend of his/(c) had given him/(d) a very good news./(e) No error"],
					["8. (a) I don't like/ (b) that kind of a man/(c) who does nothing but/(d)find out faults in others. / (e) No error"],
					["9. (a) Little knowledge/(b) of art that she possessed/(c) proved to be a boon for her/ (d) when she was utterly helpless./(e) No error"],
					["10. (a) Don't talk to her/(b) she always/(c) remains in temper/(d) these days./(e) No error"],
					["11. (a) She boasts of/(b) having good knowledge/(c) of Physics but everybody/(d) knows how far she is good at it./ (e) No error"],
					["12. (a) It was/(b) by a mistake/(c) that she caught/(d) his hand./ (e)No error"],
					["13. (a) The order of/(b) the commander/(c) may put the lives of/(d)many soldiers in a danger./No error"],
					["14. (a) She Inspired me/(b) to take the heart/(c) in all adverse situations/(d) and deserve to be called a real hero./(e) No error"],
					["15. (a) The most happy/(b) marriage would be/(c) a union of a deaf/(e)man to a blind woman. /(e) No error"],
					["16. (a) Sam suggested to/ (b) his siblings that they should/(c) go to the school regularly/(d) and do their home work sincerely./(e) No error"],
					["17. (a) Her father/(b) forbade her to go/(c) to circus /(d) late at night./(e) No error"],
					["18. (a) There was little milk/(b) in the bottle and she gave it/(c) to her son when he/(d) started weeping./ (e) No error"],
					["19. (a) In a hour's time/(b)when I had finished the work/(c) I got up and/(d) slipped out unnoticed./(e) No error"],
					["20. (a)People in Pakistan/(b) had become so accustomed to bomb blasts/(c) that few of them paid any attention to the explosions/(d) which they heard this morning/(e) No error"],
					["21. (a) One should/(b) be true to one's promises/(c) in order to earn/(d) name and fame in the life/(e) No error"],
					["22. (a) 'Management is science/(b) as well as an art'/(c) said the/(d)Business teacher./(e) No error"],
					["23. (a) It is a pity/(b) that the son of freedom fighter/(c) should indulge/(d) in stealing./(e) No error"],
					["24. (a) This is/(b) the most important/(c) question of this topic which you have/to prepare very carefully/No error"],
					["25. (a) Nile is/(b) the longest /(c) river of /(d) the world./(e) No error"],
					["26. (a) The Ganges/(b) is for India/(c) what Amazon/(d) is for Brazil./(e) No error"],
					["27. (a) The first Afghans/(b) to rule India/(c) in medieval times/(d)were the Lodhis./(e) No error"],
					["28. (a) The warden/(b) asked the boys to return/(c) to the hostel before/(d) the sunset./(e) No error"],
					["29. (a) She found/(b) herself in trouble/(c) when he saw no/(d) rickshaw outside the station./(e) No error"],
					["30. (a) She said/(b) that he did not feel/(c) any need to discuss/(d) the episode in the detail./(e) No error"],
					["31. (a) It is very difficult /(b) to point out the number of/(c) microbes living/(d) on the earth./(e) No error"],
					["32. (a) Of the two/(b) sisters she/(c) is/(d) worse./(e) No error"],
					["33. (a) I have been/(b) informed that Mr. Verma, /(c) the CEO and the MD /(d) will visit Mumbai the following month. /(e) No error"],
					["34. (a) I inspired him/(b) to take the action/(c) in all adverse situations/(d) and emerge out to be a true winner./ (e) No error"],
					["35. (a) The Indian peoples/(b) are considered/(c) very brave/(d) and honest./(e) No error"],
					["36. (a) He leads/(b) a very simple life/(c) so he goes to his office/(d) by a bicycle./(e) No error"],
					["37. (a) Thanks to an effort/(b) and persistence of the doctors the Cancer patient/(c) has been able to start /(d) a normal life again. /(e) Noerror."],
					["38. (a) Naxalites /(b) kill innocent people/(c) to spread/(d) a violence./(e) No error"],
					["39. (a) The answer/(b) to all the sufferings/(c) of human beings /(d)lies in the science./(e) No error"],
					["40. (a) The man/(b) is the only creature/(c) that is endowed with/(d)the ability to think./(e) No error"],
					["41. (a) It is very difficult/(b) to find out the number of/(c) the creatures living /(d) on the earth./(e) No error"],
					["42. (a)The earthquake derailed the lives/(b) of many people but in an year/ (c) time leaving apart the victims/(d) ,no one remembered anything/(e)No error"],
					["43. (a) Mother in him/(b) could not bear/(c) the condition of /(d) his ailing son/(e) No error"],
					["44. (a) Let judge in you/(b) decide what/(c) punishment should be/(d) given to the culprit./(e) No error"],
					["45. (a) My teacher /(b) said that/(c) Moon is a/(d) natural satellite/(e)No error"],
					["46. (a) Most of the people/(b) of northern India/(c) do not know /(d)the Telugu /(e) No error"],
					["47. (a) She went for /(b) the lunch /(c) at 1 p.m. and/(d) then returned/(e) No error"],
					["48. (a) Every morning/(b) the Sun/(c)sets in/(d) west/No error"],
					["49. (a) Now a days,/ (b) Kohli is/(c) best player/(b) in India/(e) Noerror."],
					["50. (a)When I met her/(b) the couple of days/(c) back she was writing/(d) a new book/(e) No error"],
					  
						
						
					[ "Now OVER!!! Just rate us!"]
							]
						
				

	
				
				
				
sol =    [			"Lets Start!",
					"1. (b); 'A movie' should be used in place of 'the movie because we are not talking about any particular movie. Hence article 'a' will be used in place of the",
					"2. (d); 'The better' should be used in place of 'better'. Because when a choice is to be made, we use 'the' before a comparative degree",
					"3. (c); 'The' should be used before few. Since, 'the few' means 'some' and 'few friends' means 'almost no friends' ",
					"4. (d); 'a centre of attraction' should be replaced with 'the centre of attraction'. Since, 'the' follows the former noun in sentence with the structure 'none + of + noun'. For eg 'The art of living.'",
					" 5. (e); No error ",
					"6. (d); 'The' should be used before 'least' since superlatives degrees are always preceded by 'the'",
					"7. (d); 'a' should not be used, since 'news' is an uncountable noun",
					"8. (b); 'a' should not be used because an 'Article' is not used with nouns followed by 'type of', 'kind of', 'sort of' etc",
					"9. (a); 'The' should be used before 'little'. 'The little' means 'all that is' whereas, 'little means almost none",
					"10. (c); 'in a temper' should be used in place of 'in temper'. Since it is the correct phrasal use",
					"11. (b); 'a good knowledge' is correct phrase",
					"12. (b); 'By mistake' should be used instead of 'by a mistake' as it is correct idiomatic usage",
					"13. (d); 'in danger' is correct phrase",
					"14. (b); 'the' should not be used. Since 'take heart', 'take action', 'take care', etc. are correct phrases",
					"15. (c); 'the union' should be used in place of 'a union' for explanation refer to question - 4",
					"16. (c); 'the' should not be used before 'school' since, here, school is mentioned in relation to its primary motive",
					"17. (c); ' Go to the circus' is correct idiomatic usage",
					"18. (a); 'a' should be used before 'little'. 'A little' means 'some though not much' whereas 'little' means 'almost none'",
					"19. (a); 'an' should be used in place of 'a' since 'hour' starts with a vowel sound",
					"20. (e); No error",
					"21. (d); 'The' should not be used before 'life'. Because when 'life', 'Science', 'man', etc. are used in general sense, then, 'the' is not used before them",
					"22. (a); 'a' should be used before science. Since, 'Science' has not been used in general sense here. it has been used to denote a particular branch of knowledge based on scientific principles",
					"23. (b); 'a' should be used before 'freedom fighter' since 'freedom fighter' is a countable noun",
					"24. (e); No error",
					" 25. (a); 'The' should be used before 'Nile' since 'Nile' is a river",
					"26. (c); 'The' should be used before 'Amazon' since 'Amazon' is a river.",
					"27. (e); No error",
					"28. (d); 'The' should not be used before 'sunset' since, 'the' is not used before 'dawn', 'Sunset', 'sunrise' etc",
					"29. (b); 'in a trouble' is correct idiomatic usage",
					"30. (d); 'in detail' is correct idiomatic usage",
					"31. (e); No error ",
					"32. (d); 'the' should be used before 'worse'. For explanation refer to question – 2",
					"33. (c); 'the' should not be used before 'MD' since both the posts are held by Mr. Verma",
					"34. (b); 'take action' is correct idiomatic usage",
					"35. (a); 'People' denotes people of different ethnic groups. Whereas, the word 'Indian' denotes only one group of people Hence either 'The Indians' or 'the Indian people' should be used",
					"36. (d); 'by bicycle' is correct idiomatic usage",
					"37. (a); Here the efforts of the doctors are being talked about. Hence, 'the' should be used before effort",
					"38. (d); 'violence' is an uncountable noun. Hence 'a' should not be used",
					"39. (d); 'The' is not used with the name of any subject",
					"40. (a); 'The' should not be used before 'man' for explanation refer to question -21 ",
					"41. (c); The should not be used: for explanation refer to question – 4",
					"42. (b); 'Year' does not begin with vowel sound. Hence, 'a' should be used in place of 'an'",
					"43. (a); 'The' should be added before 'mother'. Since, the article 'the' is used before the name of a personality, whenever, we talk about a personality inside a person",
					"44. (a); 'The' should be added before 'Judge'. For explanation refer to question 43",
					"45. (c); 'The' should be added before 'moon' since 'the' is used before the name of a heavenly body",
					"46. (d); 'The' is not used before the names of languages",
					"47. (b); 'The' should not be used since the names of meals do not take any article",
					"48. (d); 'The' should be used before 'west' since definite article 'the' is used before the names of directions",
					"49. (c); 'The' should be used before best",
					"50. (b); 'a couple of days' is correct phrase",
					
					"Thnx for Joining"

				
				
				]

