questions=        	 [  [ "  Quiz CONDITIONAL  SENTENCES & Conjuctions: will start in 30 secs. " ],
						
						["1. (a) If she will work/ (b) hard she/(c) will surely / (d) clear the exam. / (e)  No error" ],
						["2. (a) Before the teacher /(b) will come you / (c) should better / (d) complete your test. / (e)  No error" ],
						["3. (a) We will come to/(b) know the winner / (c) after the / (d) result is declared. / (e)  No error" ],
						["4. (a) Until the bus/(b) will not get the signal, /(c) it will not / (d) leave the stand. / (e)  No error" ],
						["5. (a) If she had money/ (b) she will have/ (c) lent it/ (d) to me. / (e)  No error" ],
						["6. (a) If I was you/ (b) I would not/(c) tolerate her / (d) for a moment. / (e)  No error" ],
						["7. (a) Suppose he/(b) does not attend the meeting/ (c) what could/ (d) we do ? / (e)  No error" ],
						["8. (a) Supposing if he /(b) does not reach / (c) the examination centre in time, / (d) what will his teacher do? / (e)  No error" ],
						["9. (a) If you saw / (b) a ghost what / (c) will your/ (d) reaction be?/ (e)  No error" ],
						["10. (a) If I had/(b) two cars, / (c) I would have given / (d) one to you./ (e)  No error" ],
						["11. (a) If we will/(b) heat camphor / (c) it turns / (d) to vapour. / (e)  No error" ],
						["12. (a) Suppose if you are / (b) late, you will not be / (c) allowed to enter the examination hall. / (e) No error."],
						[" 13. (a) Unless / (b) he will not understand/(c) the importance of this project/ (c) he will not /(d) work sincerely. / (e)  No error" ],
						["14. (a) If he tried again,/ (b) he can win/(c) the race/ (d) with decent margin. / (e)  No error" ],
						["15. (a) I will wait/ (b) for her / (c) unless / (d) she comes. / (e)  No error" ],
						["16. (a) If I was / (b) you I / (c) would never/ (d) talk to him . / (e)  No error" ],
						["17. (a) If I were / (b) the Richest person of India / (c) I will work for the / (d) welfare of the poor. / (e)  No error" ],
						["18. (a) If he would have come to me / (b) I would have / (c) given him the / (d) money he needed / (e)  No error" ],
						["19. (a) If he worked/ (b) he can /(c) get the job / (d) in time / (e)  No error" ],
						["20. (a) If I was /(b) a Rockstar/ (c) I would visit / (d) every country of the world / (e)  No error" ],
						["21. (a) If both of/(b) you hit / (c) the wooden box / (d) it would have broken./ (e)  No error" ],
						["22. (a) If he would have worked hard, / (b) he would / (c) have topped/ (d) the exam. / (e)  No error" ],
						["23. (a) If he had seen his father, / (b) he would have /(c) stopped his car / (d) and come to him. / (e)  No error" ],
						["24. (a) If the Principal will make strict rules/ (b) the unruly/(c) students will come / (d) under control. / (e)  No error" ],
						["25. (a) But for/(b) his help / (c) his sister would / (d) have failed . / (e)  No error" ],
						["26. (a) But for his hard work / (b) his family /(c) members would/ (d) have suffered a lot. / (e)  No error" ],
						["27. (a) I will not be/ (b) able to come / (c) in case / (d) it will rain. / (e)  No error" ],
						["28. (a) Had the river/(b) overflown its bank,/ (c) flood would / (d) have come. / (e)  No error" ],
						["29. (a) Had I known his intentions, / (b) I would not allow/(c) him to enter/ (d) my house. / (e)  No error" ],
						["30. (a) You will not get good marks / (b) unless you will not / (c) follow the /(d) teacher's instructions. / (e)No error" ],
						["31. (a) Supposing if /(b)she refuses / (c) to help you, / (d) what will you do? / (e)  No error" ],
						["32. (a) I shall take you for lunch /(b) after you /(c) will return/(d) from the meeting. / (e)  No error" ],
						["33. (a) When you complete your service / (b) you will be / (c) retired / (d) on pension. / (e) No error"],
						["34. (a) Were she I, / (b) she will not allow/ (c) her son to/(d) go out at night./ (e)  No error" ],
						["35. (a) I told her when / (b) she went to Mumbai,/ (c) my brother would show her/(d) all historical monuments. / (e)No error"],
						
						[" Conjuction started: 1. (a) The period between / (b) 2000 to 2010 was very / (c) significant in my life. / (d) No error"],
						["2. (a) Your success in IAS examinations depends not only on / (b)what papers you have selected / (c) but on how you have written them. / (d) No error"],
						["3. (a) I haven't been to / (b) New York before and / (c) neither my sister. / (d) No error"],
						["4. (a) The reason why he / (b) was rejected was because / (c) he was too young. / (d) No error"],
						["5. (a) Scarcely had I bought / (b) the ticket when the train / (c) left the platform with a hissing sound. / (d) No error"],
						["6. (a) None of the diplomats at the conference / (b) was able either to/ (c) comprehend or solve the problem. / (d) No error"],
						["7. (a) We are extremely pleased / (b) for excited as well to invite you/ (c) to attend the meeting. / (d) No error"],
						["8. (a) Bread and butter / (b) is / (c) all we want. / (d) No error"],
						["9. (a) He walked as faster / (b) as he could so that / (c) he would not miss the train to work. / (d) No error"],
						["10. (a) No sooner the teacher / (b) enter the class / (c) than the students stood up / (d) No error"],
						["11. (a) Keep him at the arm's length / (b) lest you may not repent / (c)in the long run. / (d) No error"],
						["12. (a) Unless you do not meet / (b) all the requirements / (c) your application will be rejected. / (d) No error"],
						["13. (a) No sooner she had realized / (b) her blunder than she began / (c)to take corrective measures. / (d) No error"],

						["14. (a) Neither the doctor nor the nurses / (b) were asleep when / (c)the injured was brought to the hospital. / (d) No error"],
						["15. (a) This is perhaps the same place who / (b) was chosen by us / (c)for the picnic. / (d) No error"	],	
						
						[ "Now OVER!!! Just rate us!"]
							]
						
				

	
				
				
				
sol=[				"Lets Start!",
					"1. (a); Change 'If she will work hard' into 'If she works hard '. 'Will' is not used in the 'If clause'",
					"2. (b); Change 'before the teacher will come' into 'before the teacher comes '",
					"3. (d); Change 'result is declared' into 'result has declared'. If the 2nd action takes place after the 1st action has already finished, the 1st action will be in present perfect tense",
					"4. (b); Remove 'will not'. 'Not' and 'will' do not come after 'unless'. Change 'get' into 'gets'",
					" 5. (b); Change 'will have lent' into 'would lend'. See the given formula- If + S + V2 , S + would + V1",
					" 6. (a); Change 'was' into 'were'. 'Was' is not used in imaginary sentence",
					"7. (c); Change 'could' into 'can'. The sentence is not of past ability",
					"8. (a); Remove 'if' .'supposing' and 'if' mean the same. When used together, they make the sentence superfluous",
					"9. (c); Change 'will' into 'would'",
					"10. (c); Change 'I would have given' into 'I would give'",
					"11. (a); Remove 'will'",
					"12. (a); Remove 'if. 'Suppose' and 'if mean the same. When used together, they make the sentence superfluous",
					"13. (b); Change 'he will not understand' into 'he understands'.'Not' and 'will' do not come after 'unless'",
					"14. (b); Change 'can' into 'could'. The sentence is in past",
					"15. (c); Change 'unless' into 'until'. Until is time oriented whereas unless is action oriented",
					"16. (a); Change 'was' into 'were'. 'Was' is not used in imaginary position",
					"17. (c); Change 'will' to 'would'",
					"18. (a); Change 'If he would have come' into 'If he had come'. See the given formula- If + S + had + V3 , S + would + have + V3 ",
					"19. (b); Change 'can' into 'could'. The sentence is in past",
					"20. (a); Change 'was' into 'were'. 'Was' is not used in imaginary position",
					"21. (d); Change 'would have broken' into 'would break'. The sentence fits in the formula given below- If + S + V2 , S + would + V1 ",
					"22. (a); Change 'If he would have worked hard' into 'If he had worked hard'. The sentence fits in the formula given below– If + S + had + V3 S + would + have + V3 ",
					"23. (e); No error",
					"24. (a); Change 'If the Principal will make' into 'If the Principal makes''Will' is not used in the 'If clause'",
					"25. (e); No error. here 'but for' means 'without'",
					"26. (e); No error. Here 'but for' means 'without'",
					"27. (d); Change 'It will rain' into 'it rains'",
					"28. (b); V3 of 'overflow' is 'overflowed'",
					"29. (b); Change 'I would not allow' into 'I would not have allowed'. The sentence fits in the formula given below- Had + S + V3 , S + would + have + V3 ",
					"30. (b); Remove 'will not'. 'Not' and 'will' do not come after 'unless'",
					"31. (a); Remove 'if'. 'Supposing' and 'if' mean the same. Together they make the sentence superfluous",
					"32. (c); Change 'will return' into 'have returned'. If the 2nd action takes place after the 1st action has already finished, the 1st action will be in present perfect tense",
					"33. (a); 'When you have completed your services' is correct usage. If the 2nd action takes place after the 1st action has already finished, the 1st action will be in present perfect tense",
					"34. (b); Change 'will' into 'would'. The sentence is in past",
					"35. (a); Add 'that' after 'I told her' because a sentence is connected to the other sentence with the help of a conjunction",
					
					"1. (b); 'between' is followed by 'and' and not 'to'.",
					"2. (c); 'But also' is used together with 'not only'. Add 'also' to 'but'",
					"3. (c); 'Neither' is followed by 'helping verb' and then the subject.'Neither has my sister' is the correct sentence form.",
					"4. (b); 'because' cannot come with 'the reason why' because the sentence then becomes superfluous.",
					"5. (d); No error.",
					"6. (b); In the given sentence comprehend and solve are the two verbs, either must come before 'comprehend' because 'or has been used before 'solve'. Put 'either' after 'to'",
					"7. (b); Change 'for' into 'and'",
					"8. (c); Add 'that' after 'all'.",
					"9. (a); With 'as….. as' the adjective/ adverb will come in their positive degree. Change 'faster' into 'fast'.",
					"10. (a); 'No sooner' is followed by 'a helping verb' and the 'sub'. 'No sooner did the teacher' will be the correct sentence form.",
					"11. (b); Change 'may' into 'should' as 'Lest … should' are together used as conjunction.",
					"12. (a); 'Unless' is not followed by 'not'. 'Unless you meet' will be correct sentence formation.",
					"13. (a); 'Had' must come after 'no sooner' and the subject must follow.",
					"14. (d); No error",
					"15. (a); 'The same' is followed by 'that' and moreover 'who' is not used for places.",


					"Thnx for Joining"
						
						]

