questions = [
			 [ "  Noun Quiz will start in 30 secs. " ],
						
			["1. (a) He knows it well/(b) that his success in life/(c) depends not on my advice/(d) but on somebody else./(e) No error"],
			["2. (a) She informed me/(b) that she had gone to/(c) one of the MLA’sresidences/(d) and stayed there all day./(e) No error"],
			["3. (a) I visited/(b) Rajesh’s and Seema’s house/(c) twice but found/(d) the couple absent./(e) No error"],
			["4. (a)The building’s roof/(b) needs repairing otherwise it /(c) mayfall down and/(d) result into many persons’ death./(e) No error"],
			["5. (a) A gram’s weight/(b) is quite light for/(c) anyone to/(d) carry on his head./(e) No error"],
			["6. (a) I stopped/(b) her going out late at night/(c) because the situation/(d) in the town was very tense./(e) No error"],
			["7. (a) She did not approve/(b) of her son raising/(c) stupid questions and there by/(d) annoying his tutor. /(e) No error"],
			["8. (a) India’s problems/(b) are however /(c) not so serious/(d) and awful as Pakistan./(e) No error"],
			["9. (a) His tone of speaking/(b) as well as his friends/(c) is really extremely rude/(d) yet we never take it seriously./(e) No error"],
			["10. (a) The Defence Minister/(b) boasts of improving /(c) the military power of/(d) the country’s./(e) No error"],
			["11. (a) The life of the homeless people/(b) is not in many/ (c) ways aspeaceful and luxurious/(d) as that of the rich’s/(e) No error"],
			["12. (a)The CEO of the company said/(b) that he appreciated/(c) his staffs coming on time/(d) and co-operating him./(e) No error"],
			["13. (a) As the students were told /(b) this idea of Mahatma Gandhi’s/(c) was totally valid in the/(d) present condition of India./(e) No error"],
			["14. (a) It is true/(b) that I met/(c) the Prime Minister/(d) at the house of one of my relative’s./(e) No error"],
			["15. (a) The priest said/(b) to his followers that one ought/(c) to work hard in order/(d) to attain one goal./(e) No error"],
			["16. (a) Being sure of her/(b) success, she told her parents/(c) that she would never forget/(d) even her enemies’s names./(e) No error"],
			["17. (a) The plebiscite gives/(b) us much knowledge of the/(c)Public’s opinion/(d) on the matter of rape./(e) No error"],
			["18. (a) No soldier/(b) dared to turn/(c) a deaf ear to his/(d)commander’s-in-Chief orders./(e)No error"],
			["19. (a) I appreciate she/(b) helping the destitute/(c) who are really the most ignored and completely deprived/(d) section of our society./(e) No error"],
			["20. (a)I have read/(b) many poems of Tagore’s /(c) who is also/(d)known as Gurudev./(e) No error"],
			["21. (a) A friend of my wife /(b) came to me/(c) last week and askedme for/(d) some help./(e) No error"],
			["22. (a) Unfortunately for us/(b) the root cause of our frustration lies/(c) in the Governments/(d) ineffective policy/(e) No error"],
			["23. (a) She suggested to me/(b) that I should go to the market/(c) to bring some beautiful/(d) summer’s flowers./(e) No error"],
			["24. (a) He came to his wits end/(b) when he found/(c) that his younger/(d) brother had slapped his wife./(e) No error"],
			["25. (a) When she arrived/(b) at the gate of his/(c) house, she found his/(d) locking up the door./(e) No error"],
			["26. (a) India and Pakistan’s present/(b) condition clearly indicate/(c)that both the countries/(d) will face a lot of problems in the coming time./(e) No error"],
			["27. (a) Keeping in view/(b)the public’s demands/(c ) the government has decided to introduce a new policy to improve the quality and lower/(d) the prices of food grains./(e) No error"],
			["28. (a) Many a citizen’s life is in danger/(b) if the Government doesnot take/(c) any serious action to/ (d) curb degradation of environment. /(e) No error"],
			["29. (a) My brother/(b) has read/(c) pages after pages/(d) of the Ramayana./(e) No error"],
			["30. (a) He went to/(b) the church with/(c) his parents, aunts/(d) and cousin sisters/(e) No error"],
			["31. (a) She/(b) takes pain/(c) over her/(d) work. /(e) No error"],
			["32. (a) Teacher told/(b) students that/(c) radiuses of a circle /(d) are always equal./(e) No error"],
			["33. (a) I like/(b) the poetries/(c) of Rabindranath Tagore /(d) and Harivansh Rai Bachchan./(e) No error"],
			["34. (a) The sceneries/(b) of Uttarakhand/(c) is very/(d) charming/(e) No error"],
			["35. (a) Whenever she goes/(b) to Mumbai/(c) she stays in/(d)World-classes hotels./(e) No error"],
			["36. (a) She was advised /(b) to take/(c)two spoonsful of/(d)medicine twice a day./(e) No error"],
			["37. (a) The police have received/(b) three important informations/(c)that helped them solve/ (d) the robbery case/(e) No error"],
			["38. (a) All his brother-in laws/(b) are extremely co-operative/(c) and she doesn’t miss her/(d) real brothers at all./(e) No error"],
			["39. (a) He will not/(b) go to party tonight/(c) since he has/(d) manyworks to complete./ (e) No error"],
			["40. (a) He wears spectacle/(b) and so he was /(c) unable to see the burglar /(d) that attacked him last month./(e) No error"],
			["41. (a) Most of the furnitures were/(b) sold for a song/(c) as the seller was in a hurry/(d) to leave the town./(e) No error"],
			["42. (a) She left/(b) her luggages/(c) at home by mistake and /(d)went to the railway station./ (e) No error"],
			["43. (a) Sheila Dixit had/(b) been the administrator of Delhi/(c) for more/(d) than ten years./(e) No error"],
			["44. (a) I think this/(b) is not your car/(c) It is/(d) somebody’s else./(e) No error"],
			["45. (a) One should not put/(b) one’s sign /(c) on any paper/(d) that one hasn’t read./(e) No error"],
			["46. (a) Towns after towns were/(b) conquered/ (c) by Alexander but/(d) he found no peace anywhere./ (e) No error"],
			["47. (a) Even after hours of discussion/ (b) the committee/(c) could not come/(d) to a final conclusion./(e) No error"],
			["48. (a) The cattle in the grazing ground/ (b) was terrified to hear/(c)the roar of a lion which/(d) appeared to be wild with anger./(e)No error"],
			["49. (a) This house/(b) is not built/(c) of stones/(d) but of love./(e)No error"],
			["50. (a) I am looking/(b) for a lady tailor/(c) to stitch a dress/(d) for my daughter./(e) No error"],


			[ "Now OVER!!! Just rate us!"]
							]
						
				

	
				
				
				
sol=    [				"Lets Start!",
						
						"1. (d); Apostrophe‘s’ (‘s) should be added to else. i.e. ‘else’s’ should be used in place of ‘else’ to show a relation’ ",
						"2. (c); ‘ Residence of one of the MLAs ’ should be used in place of ‘ one of the MLA's residences since the possession of nouns used with ‘one of’ is not denoted by apostrophe’s",
						"3. (b); ‘Rajesh and Seema’s’ should be used in place of ‘Rajesh’s and Seema’s’. When two nouns are closely related then apostrophe‘s’ is used only after the latter one",
						"4. (a); ‘The building’s roof’ should be replaced with ‘The roof of the building’ since, apostrophe‘s’ is not used with non living things",
						"5. (e); No error. ‘A ton’s/gram’s/kilo’s weight’ is correct usage",
						"6. (e); No error",
						"7. (b); Here ‘son’s’ should be used since gerunds are always preceded by possessive case",
						"8. (d); ‘Pakistan’s’ should be used in place of ‘Pakistan’ Since the problems Pakistan is having, have been compared with those of India and hence, apostrophe’s’ should be added to Pakistan",
						"9. (b); ‘Friend’s’ should be used in place of ‘friends’ to show the possession of a quality (tone of speaking)",
						"10. (d); ‘Country’ should be used in place of ‘Country’s’ since the phrase ‘of the’ already shows the possession hence use of apostrophe’s’ is superfluous",
						"11. (d); ‘rich’ should be used in place of ‘rich’s’. Since, ‘that of’ shows ‘the life of poor’s’, hence, the use of apostrophe is superfluous",
						"12. (c); ‘ Staff’s ’ should be used in place of ‘staffs'. For explanation refer to question-7",
						"13. (b); ‘Gandhi’ should be used in place of ‘Gandhi’s. Since the sentences with structure ‘This/That/These/Those of’ do not take possessive case after ‘of’",
						"14. (d); ‘the house of one of my relative’ should be replaced with ‘the house of one of my relative’s’ for explanation refer to question-2",
						"15. (d); ‘One’s’ should be used in place of ‘one’",
						"16. (d); 'enemies’ ' should be used in place of ‘enemies’s ’ since, we put an Apostrophe comma at the end of plurals formed by adding ‘s’ at the end like seniors’, friends’, Boys’, etc",
						"17. (c); ‘Public opinion’ should be used in place of ‘public’s opinion‘ since ‘public’ has been used as adjective and generally, ‘s’ is not used with adjectives",
						"18. (d); ‘commander-in-chief’s ‘ should be used in place of ‘commander’sin-chiefs ‘. Since apostrophe is added only at the end of compound words",
						"19. (a); ‘her’ should be used in place of ‘she’ since gerunds are always preceded by possessive case",
						"20. (b); ‘Tagore ‘ should be used in place of ‘Tagore’s ’ since in sentences with structure 'Many + noun + of + noun', the latter noun does not take possessive case",
						"21. (a); ‘wife’s’ should be used in places of ‘wife’ since in sentences with structures ‘A noun + of + noun’ ‘apostrophe’ is used with the latter noun",
						"22. (c); ‘Government’s ’ should be used in place of ‘Governments ’ ",
						"23. (d); ‘Summer flower’ should be used in place of ‘summer’s flower’, since, ‘Apostrophe’s is not used with the names of seasons",
						"24. (a); At one’s wit’s end is correct idiomatic usage",
						"25. (c); ‘him’ should be used in place of ‘his’ since ‘locking’ has been used as participle and not as gerund. Hence objective case should be used",
						"26. (a); ‘India’s ‘ should be used in place of ‘India’. When two nouns are joined with ‘and’ and denote two different possessions, then ‘apostrophe’ is used with each of them",
						"27. (b); ‘Public demand’ should be used in place of ‘Public’s demand’ For explanation, refer to question -17",
						"28. (e); No error",
						"29. (c); ‘Page after page’ should be used in place of ‘pages after pages’. Since, a noun in singular form in used on the either side of a preposition",
						"30. (d); ‘Cousins’ should be used in place of ‘cousin sisters’",
						"31. (b); ‘take pains’ is the correct idiomatic usage",
						"32. (c); ‘Radii’ (not radiuses) is plural of ‘Radius’",
						"33. (b); ‘Poetry’ is an uncountable noun and hence, it does not have any plural form",
						"34. (a); ‘Scenery’ should be used in place of ‘Sceneries’, Since, scenery is an uncountable noun",
						"35. (d); ‘World-class’ should be used in place of ‘world-classes’ since, hyphenated nouns are always used in singular form",
						"36. (c); ‘Spoonfuls’ should be used in place of ‘spoonsful’ ",
						"37. (b); ‘Information’ should be used in place of ‘informations’ since information is an uncountable noun. However, we can make it countable and plural by using ‘pieces of information’",
						"38. (a); ‘Brothers-in-law’ should be used in place of ‘Brother-in-laws’",
						"39. (d); ‘some work’ should be used in place of ‘many works’ since work is an uncountable noun. We can also use either ‘much’ in place of ‘many’ or ‘many pieces of work’ in place of ‘many works’",
						"40. (a); ‘Spectacle’ should be changed into ‘spectacles’ ",
						"41. (a); ‘Furniture’ should be used in place of 'furnitures' since furniture is an uncountable noun",
						"42. (b); ‘luggage’ should be used in place of ‘luggages’ ",
						"43. (b); ‘administratrix’ should be used in place of ‘administrator’. Since, ‘administratrix’ is the feminine form of administrator",
						"44. (d); ‘Somebody else’s ‘ should be used in place of ‘somebody’s else ‘For explanation refer to question-1",
						"45. (b); ‘Signature’ should be used in place of ‘sign’. Since, ‘sign’ is a verb and ‘signature’ is a noun",
						"46. (a); ‘Town after Town’ should be used in place of ‘Towns after Towns’ For explanation refer to question-29",
						"47. (d); Remove ‘final’ as conclusion is always final. Hence, usage of final is superfluous",
						"48. (b); ‘were’ should be used in place of ‘was’ since ‘cattle’ is a plural noun",
						"49. (c); ‘Stone’ should be used in place in place of ‘stones’ ",
						"50. (b); ‘Tailoress’ should be used in place of ‘lady tailor’. Since ‘Tailoress’ is feminine of ‘tailor’",
						"Thnx for Joining"
					
							]


						
						
					