questions =  [
						[ " Quiz Preposition: will start in 30 secs. " ],
						["1. (a) She along with /(b) her friends took/(c) leave of/(d) a week./(e)No error."],
						["2.One should always/(b) listen the advice of/(c) one's elders/(d)and well wishers./(e) No error"],
						["3. (a) She will/(b) not listen what /(c) you say/(d) to her./(e) No error"],
						["4. (a) Nobody denies/(b) that /(c) my ideas are/ (d)different than yours./(e)No error"],
						["5. (a) It was she/ (b) who was responsible of /(c) making all thearrangements for/(d) the successful completion of his business trip./(e) No error"],
						["6. (a) He was in the bathroom/(b) when the burglars/(c) entered into/(d) his house./(e) No error"],
						["7. (a) Their teacher/(b) emphasized on/(c) the use of /(d) correctgrammar./(e) No error"],
						["8. (a) On the time/(B) of the opening ceremony/(c) of the theatre,/(d) alarge crowd had assembled./ (e) No error"],
						["9. (a) While Rajesh was returning/(b) from school/(c) a stalker attackedon him/(d) with a knife./ (e) No error"],
						["10. (a) The decline of/(b) her moral values has caused/(c) a lot of /(d) painto her parents./(e) No error"],
						["11. (a) Without thinking/(b) for a moment/(c) she entrusted him in/(d)all the responsibilities./(e) No error"],
						["12. (a) Sandy and her sister/(b) fell in/(c) the well and nobody/(c) triedto save them./(e) No error"],
						["13. (a) I/(b) prefer coffee/(c) than/(d) tea/(e) No error"],
						["14. (a) Sumit is busy/(b) in his/(c) preparations for/(d) his exams./(e) Noerror."],
						["15. (a) While crossing the road/(b) a child was/(c) run out by/(d) aspeeding car./(e) No error"],
						["16. (a) We were taught that/(b) amphibians can live/(c) in water/(d) aswell as land./(e) No error"],
						["17. (a) My father is/ (b) fond off/(c) cooking different/(d) types of cakes./(e) No error"],
						["18. (a) Your teacher/ (b) cannot/(c) control on/ (d) the students./(e) Noerror"],
						["19. (a) The Jury has been/(b) waiting for/(c) the prisoner/(d) for 2 P.M./(e) No error"],
						["20. (a) Mr. Uniyal has/(b) great affection towards/(c) his family /(d) andfriends./(e) No error"],
						["21. (a) Rani has/(b) a great/(c) enmity for/(d) her brother's friend./(e)No error"],
						["22. (a) She threw the bucket/(b) into the well/(c) and returned home/(d)without any water./(e) No error"],
						["23. (a) There appears/(b) to be very little/(c) understanding among /(d)the two friends./(e) No error"],
						["24. (a) He was angry on/(b) me because I had/(c) not invited him/(d) tothe party./(e) No error"],
						["25. (a) She got a prestigious job/(b) though she was/(c) not worthy/(d)for it/(e) No error"],
						["26. (a) He described about/(b) the incident/(c) in a very/(d) interestingway/(e) No error"],
						["27. (a) Shyam tells/(b) Sunder that his/(c) father deals with/(d)cosmetics./(e) No error"],
						["28. (a) Shipra cannot/(b) deal from/(c) those unruly/(d) children./(e) Noerror"],
						["29. (a) Despite of/(b) working hard/(c) he failed/(d) the test/(e) No error"],
						["30. (a) Sonu/(b) married with/(c) Neelu despite/(d) their family'sobjection. /(e) No error"],
						["31. (a) The earth's/(b) atmosphere comprises/(c) of three/(d) differentlayers./(e) No error"],
						["32. (a) The court held/ (b) the local politician responsible/(c) for the lossor damage to/(d) any public property./(e) No error"],
						["33. (a) She was/ (b) debarred to attend/(c) the monsoon session/ (d) ofthe parliament./(e) No error"],
						["34. (a) She should refrain to/(b) associating herself with /(c) any politicalparty because people/(d) have faith in her integrity. /(e) No error"],
						["35. (a) The songs of/(b) this movie are/(c) worth listening/(d) to/(e) Noerror."],
						["36. (a) I certainly/(b) differ with/(c) you in/(d) this matter./(e) No error"],
						["37. (a) He had a suspected/(b) tumor so he was/(c) admitted to /(d) thehospital/(e) No error"],
						["38. (a) If he puts/(b) his heart to it/(c) he will be/(d) a winner /(e) No error."],
						["39. (a) Today/(b) he walked/(c) twenty miles/(d) by foot/(e) No error"],
						["40. (a) He is/(b) good in science/(c) but his/(d) friends aren't./(e) Noerror."],
						["41. (a) Which /(b) newspaper/(c) does he /(d) subscribe for?/(e) No error"],
						["42. (a) It is my pleasure/(b) to congratulate him/(c) for your success /(d)in the CAT Examination./(e) No error"],
						["43. (a) She should/(b) avail herself/(c) with this/(d) golden opportunity./(e) No error"],
						["44. (a) It is/(b) half past ten/(c) in/(d) my watch/(e) No error"],
						["45. (a) Rajiv/(b) told to/(c) his father to/(d) buy a house./(e) No error"],
						["46. (a) He is/ (b) accused with/(c) committing the murder/(d) of his wife/(e) No error"],
						["47. (a) The author/(b) described the /(c) beauty of/(d) his home town./(e) No error"],
						["48. (a) The atmosphere/(b) comprises of/(c) many inert/(d) gases also./(e) No error"],
						["49. (a) We disposed off/(b) our old car/(c) before moving/(d) to Chennai./(e) No error"],
						["50. (a) She/(b) is suffering/(c) with flu /(d) since Monday./(e) No error"],

						[ "Now OVER!!! Just rate us!"]
							]
						
				

	
				
				
				
sol=    [			"Lets Start!",
					"1. (c); 'Leave for a week' should be used",
					"2. (b); 'To' should be added after 'listen'. Since 'listen' is always followed by 'to'.",
					"3. (b); 'To' should be used after 'Listen'",
					"4. (d); 'different from' should be used in place of 'different then'. Sincedifferent is always followed by form",
					"5. (b); 'for' should be used in place of 'of' since responsible is alwaysfollowed by 'of'",
					"6. (c); Use of 'into' is wrong since entered is not followed by 'into'",
					"7. (b); 'On' should be removed since emphasized is not followed by 'on'",
					"8. (a); 'At' should be used in place of 'on'. Since we are talking about aparticular Point of time (i.e. the time of the opening ceremony)",
					"9. (c); 'on' should not be used. Since 'attack' is not followed by 'on'",
					"10. (a); 'in' should be used in place of 'of' since 'decline' is followed by 'in'",
					"11. (c); 'entrusted him with' should be used in place of 'entrusted him in' Since, entrusted is followed by 'with'",
					"12. (b); 'fell into' should be used in place of 'fell in' since into denotes themovement inside something",
					"13. (c); 'to' should be used in place of 'than' since 'to' is used after 'prefer'",
					"14. (b); 'With' should be used in place of 'in'. Since 'busy' is followed by'with'",
					"15. (c); 'Run over' should be used in place of 'Run-on'. 'Run over' means'to come under the wheels of' ",
					"16. (d); 'On' should be used before land. Since 'on land' is correct phrasalusage",
					"17. (b); 'found of' should be used in place of 'fond off' since 'found' isfollowed by 'on'",
					"18. (c); 'Control' should not be followed by 'on' since, when words likecontrol, discuss. Etc. are used as verb, then they are not followedby 'on'",
					"19. (d); 'Since' should be used in place of 'for' since, we use 'since' to denotea point of time",
					"20. (b); 'for' should be used in place of 'towards' since, 'affection' is followedby 'for'",
					"21. (c); 'towards' should be used in place of 'for' since 'enmity' is followedby 'towards'",
					"22. (b); 'in' should be used in place of 'into' since 'threw' is followed by'in'",
					"23. (c); 'between' should be used in place of 'among' since 'between' isused for 'two nouns/pronouns' whereas 'among' is used for 'morethan two'",
					"24. (a); 'with' should be used in place of 'on' since we use 'with' when theobject is a person. i.e. we are 'angry with someone' and 'angry atsomething'",
					"25. (d); 'of' should be used in place of 'for' since 'worthy' is followed by'of'",
					"26. (a); Use of 'about' is superfluous. Since 'describe' is not followed byany preposition",
					"27. (c); 'Deals in' should be used in place of 'deals with'. Since, the phrasalverb 'deal in' means 'to trade'",
					"28. (b); 'Deal with' should be used in place of 'Deal from'. Since, the phrasalverb 'Deal with' means 'to handle'",
					"29. (a); 'of' should not be used. Since, 'Despite' means 'inspite of' and isnever followed by of",
					"30. (b); 'with' should not be used. Since married is not followed by with",
					"31. (c); 'of' should not be used. Since, comprise in not followed by 'of' inactive voice",
					"32. (c); 'Loss' should be followed by 'of'",
					"33. (b); 'debarred from attending' should be used Since 'debarred' isfollowed by 'from' which is again followed by a 'gerund'",
					"34. (a); 'Refrain' should be followed by 'from'. Hence 'to' should bereplaced with 'from'",
					"35. (d); 'to' should not be used since, 'worth listening' is not followed byany preposition",
					"36. (b); 'differ' is always followed by 'from' . Hence, 'with' should bereplaced with 'from.",
					"'37. (e); No error",
					"38. (b); 'Put his heart into it' is correct idiomatic usage",
					"39. (d); 'on' foot' should be used in place of 'by foot'",
					"40. (b); 'At' should be used in place of 'in'. Since, 'good' is followed by 'at'",
					"41. (d); 'for' should be replaced with 'to'. Since 'subscribe' is followed by'to'",
					"42. (c); 'on' should be used in place of 'for' since, 'congratulate' is followedby 'on'",
					"43. (c); 'of' should be used in place of with. Since 'avail' is followed by 'of' Avail himself/myself/herself/ etc of' something is correct usage",
					"44. (c); 'by my watch' is correct phrase",
					"45. (b); 'to' should not be used since neither told nor its forms are followedby 'to'",
					"46. (b); 'of' should be used in place of 'with' since 'accused' is followed by'of'",
					"47. (e); No error",
					"48. (b); 'of' should not be used. For explanation refer to question – 31",
					"49. (a); 'of' should be used in place of 'off' since 'disposed' is followed by'of'",
					"50. (c); 'from' should be used in place of 'with' since 'suffer' is followed by'from'",
						"Thnx for Joining"
						
	]

