questions =[
			[ "  Pronoun Quiz:  will start in 30 secs." ],
									
			["1. (a) Unless four or more members/(b) object to him joining / (c) theteam, we shall have to/(d) accept his application for membership./(e) No error"],
			["2. (a) He was surprised and pleased/(b) when he was/(c) informed ofhim/ (d) winning the competition./ (e) No error"],
			["3. (a) Our cat may/ (b) look fierce but/(c) that wouldn’t/(d) hurt afly./(e) No error"],
			["4. (a) No one/(b) can change/(c) destiny/(d) isn’t it? (e) No error"],
			["5. (a) All the/(b) misunderstandings are cleared/(c) between/(d)Ramesh and I./(e) No error"],
			["6. (a) The front page story/(b) was about a young boy /(c)that hadhurt himself/(d) while saving a child in an accident./(e) No error"],
			["7. (a) The last thing/(b) that the fond father/(c) gave his only daughter/(d) was her blessing./(e) No error"],
			["8. (a) It is/(b) not I/(c) who is/(d) to blame./(e) No error"],
			["9. (a) I shall avail of/(b) this opportunity/(c) to meet/(d) ShahrukhKhan there./(e) No error"],
			["10. (a)Put you/(b) in his position/(c) and you will realize/(d) theproblems faced in his profession./ (e) No error"],
			["11. (a) Each of them/(b) has to understand/(c) their importance/(d) inhis project./(e) No error"],
			["12. (a)We are happy/(b) to announce that/(c) every one of you/(d)have been promoted./(e) No error"],
			["13. (a) Here is the/(b) man whom/(c) I think assassinated/(d) theminister/(e) No error"],
			["14. (a) He took his/(b) younger daughter/(c) with himself and/(d) leftthe house./(e) No error"],
			["15. (a) The company is/(b) in debt and has been/(c) unable to pay theircreditors/(d) for the past six months/(e) No error"],
			["16. (a) The organisation has appointed/(b) consultants to help them/(c) increase its profit and/(d) Improve its financial position./(e) Noerror."],
			["17. (a) You cannot change/ (b) others but you/(c) can definitely/(d)change you./ (e) No error"],
			["18. (a) Governments and business houses must reduce/(b) its ownenergy use/(c) and promote conservation to /(d) their citizens andemployees./(e) No error"],
			["19. (a) Even those/(b) which have no/(c) proper educationqualification/(d) have applied for this exam./(e) No error"],
			["20. (a) She was talking ill of others on the phone/(b) for hours together/(c) who really irritated/(d) her parents a lot./(e) No error"],
			["21. (a) Instead of laying us off/(b) the company decided/(c) to ask us to/(d) avail us of voluntary retirement./(e) No error"],
			["22. (a) The two brothers/(b) shouted at/(c) one another/(d) in public/(e) No error"],
			["23. (a) He must supplement/ (b) his diet with /(c) calcium and proteinin order to/(d) keep himself fit./(e) No error"],
			["24. (a)Mr. Sharma/(b) being a good actor/(c) he is selected/(d) for theNational Award/(e) No error"],
			["25. (a) The poor/(b) woman poisoned her/(c) and her/(d) ownchildren/(e) No error"],
			["26. (a) It was in 2008/ (b) that we first/(c) flew to / (d) the UnitedKingdom./(e) No error"],
			["27. (a) Many a boy/(b) have /(c) failed the UPSC examination/(d)thisyear./(e) No error"],
			["28. (a) It wasn’t me/ (b) who was responsible/(c) for the debacle ofour/(d) team in the world cup./(e) No error"],
			["29. (a) John, I and you/ (b) have/(c) finished our/(d) studies/(e) Noerror."],
			["30. (a) He doesn’t/(b) know to/(c) swim in/(d) the pool./(e) No error"],
			["31. (a) All the dresses looked/(b) good and so /(c) I bought/(d) all ofit./(e) No error"],
			["32. (a) Those people/(b) who do not/(c) work hard they do not/(d)achieve their goals in life./(e) No error"],
			["33. (a) He bathe/(b) himself in/(c) a river in the afternoon/(d) of scathingsummer./(e) No error"],
			["34. (a) He/(b) could not /(c) bear/(d) her separation./(e) No error"],
			["35. (a) The leg of the table /(b) that my father/(c) had bought /(d) isbroken./(e) No error"],
			["36. (a) my school/(b) is /(c) farther than/(d) hers./(e) No error"],
			["37. (a) If he wants/(b) this job he/(c) will need/(d) your favour./ (e)No error"],
			["38. (a) I, Mohan and Mayank /(b) shall arrange everything/(c) and shallnot ask/(d) anyone for help./(e) No error"],
			["39. (a)Was it/(b)only me who /(c) had to /(d) burn the midnight oil ? /(e)No error"],
			["40. (a) The police of Delhi/(b) are better/(c) than any /(d) other state./(e) No error"],
			["41. (a) Being a minor/(b) the police admitted/(c) her to /(d) arehabilitation centre./(e) No error"],
			["42. (a) One should keep/(b) his morals intact if one wants/(c) respectfrom /(d) both friends and enemies./(e) No error"],
			["43. (a) If I were/(b) him I would teach/ (c)him a lesson which he/(d)would never forget/(e) No error"],
			["44. (a) Being a/(b) rainy day she/(c) could not/(d) go to office/(e) Noerror."],
			["45. (a) Mr. Sharma/(b) our representative/(c) he will attend /(d) themeeting on our behalf./(e) No error"],
			["46. (a) Don’t worry/(b) Myself and she/(c) will manage/(d) everything/(e) No error"],
			["47. (a) The Ganga is a river/ (b) whose importance/(c) has beenmentioned /(d) even in Vedas./(e) No error"],
			["48. (a) Neither of the two friends/(b) has got /(c) their money back/(d)from the company./(e) No error"],
			["49. (a) This is the car/(b) whose design/(c) was appreciated /(d) byeveryone./(e) No error"],
			["50. (a) My father /(b) did not object/(c) to my using/(d) his mostexpensive pen./(e) No error"],

			[ "Now OVER!!! Just rate us!"]
							]
						
				

	
				
				
				
sol=[					"Lets Start!",
						"1. (b); ‘his’ should be used in place of ‘him’ Since a gerund is always preceded by a possessive adjective",
						"2. (c); ‘his’ should be used in place of ‘him’. Since, a gerund is always preceded by a possessive adjective",
						"3. (c); ‘It’ should be used in place of ‘that’. Since, generally, ‘it’ is used as pronoun for ‘animals’ and ‘non-living things’",
						"4. (d); ‘can they’, should be used in place of ‘isn’t it",
						"5. (d); ‘me’ should be used in place of ‘I’ Since, ‘Between _____ and _____ always takes objective pronoun",
						"6. (c); ‘who’ should be used in place of ‘that’ Since, Relative pronoun ‘who’ is used as a subject in subordinate clause",
						"7. (d); ‘his’ should be used in place of ‘her’ as father will take ‘his’ as possessive adjective",
						"8. (c); ‘am’ should be used in place of ‘is’. Since the verb which follows the relative pronoun must agree with the noun/pronoun which precedes the same",
						"9. (a); Reflexive pronoun ‘himself’ should be used before ‘of’, since 'Avail + reflexive pronoun + of ' is correct syntax",
						"10. (a); ‘yourself’ should be used in place of ‘you’",
						"11. (c); ‘His’ should be used in place of ‘their’ since singular. Pronoun is used with ‘Each’ and ‘Every’",
						"12. (d); ‘has’ should be used in place of ‘have’. Since Distributive pronouns take singular form of verb",
						"13. (b); ‘Who’ should be used in place of ‘whom’. Since, ‘The man’ is the subject in this sentence, hence, ‘who’ should be used with it",
						"14. (c); ‘him ‘ should be used in place of ‘himself’",
						"15. (c); ‘its’ should be used in place of ‘their’ since ‘company’ is a singular noun, hence singular possessive adjective should be used",
						"16. (b); Since ‘organisation’ is a singular noun, Hence, ‘it’ should be used in place of ‘them’. Had it been ‘organisations’ here, then the usage of ‘them’ would have been correct",
						"17. (d); ‘yourself’ should be used in place of ‘you’",
						"18. (b); ‘their’ should be used in place of ‘its’ since. Since, Governments and business houses are plural, hence plural adjective ‘their should be used",
						"19. (b); ‘who’ should be used in place of ‘which’. Since, relative pronoun ‘who’ is used when a person (or mankind) is the subject",
						"20. (c); ‘which’ should be used in place of ‘who’. Since, ‘Talking ill of others’ is not a person but an activity. Hence ‘which’ should be used",
						"21. (d); ‘ourselves’ should be used in place of ‘us’. For explanation refer to question. 9",
						"22. (c); ‘each other’ should be used in place of ‘one another’ since for two persons ‘each other’ is used whereas for more than two persons ‘one another’ is used",
						"23. (d); ‘himself’ should be removed. Since, ‘Keep’, ‘bathe’, etc. are not followed by any reflexive pronoun",
						"24. (c); ‘He’ should be removed. Since, a noun and a pronoun cannot be used for same noun in a single sentence",
						"25. (b); ‘Himself’ should be used in place of ‘him’ when same person is the subject and object in a sentence, then reflexive pronoun is used as the object",
						"26. (b); ‘When’ should be used in place of ‘that’. Since ‘2008’ is time",
						"27. (b); ‘has’ should be used in place of have since, ‘many a’ takes singular noun and singular verb",
						"28. (a); ‘I’ should be used in place of ‘me’. Since ‘It + ’form be’ (here, was) is followed by subjective case",
						"29. (a); According to the rule 1 of uses of pronouns. ‘You, he and I’ is the correct order of pronouns that should be followed in this sentence",
						"30. (b); ‘How to swim’ should be used in place of ‘to swim’. Since, ‘wh’ family follows ‘know’ and wonder, if the verbs are in infinitive form (i.e. to + v1 )",
						"31. (d); ‘Them’ should be used in place in place of ‘it’. For explanation refer to question 16",
						"32. (c); ‘They’ should be removed from this sentence. Since ‘They’ and ‘Those’ are not used together",
						"33. (b); ‘himself’ should not be used. Since, reflexive pronoun is not used after bathe",
						"34. (d); ‘Separation from her’ is correct phrase",
						"35. (e); No error ",
						"36. (e); No error",
						"37. (d); ‘favour from you’ is correct phrase",
						"38. (a); ‘Mohan, Mayank and I’ is the correct order that should be used for reference sec question 29",
						"39. (b); ‘was it I’ should be used in place of ‘was it me’. Since, it is the interrogative form of ‘It was I’, hence the rule of usage of subjective pronoun will follow",
						"40. (c); ‘That of’ should be used between ‘than’ and’ ‘any’ since, we want to compare the police of Delhi with the police of all the other states and not with the states",
						"41. (a); ‘She’ should be added before ‘being’ because, if she is not added, then ‘the police’ becomes the subject and the sentence becomes senseless",
						"42. (b); ‘One’s’ should be used in place of ‘his’. Since, with ‘one’ as subject, ‘one’s’ is used as possessive adjective",
						"43. (b); ‘He’ should be used in place of ‘him’ since, nominative case should be used after ‘If I were’",
						"44. (a); ‘It’ should be added before ‘being’. For explanation see question41",
						"45. (c); ‘He’ should not be used here. For explanation see question – 24",
						"46. (b); ‘I’ should be used in place of ‘myself’. Since, a reflexive pronoun cannot be used as a subject",
						"47. (b); ‘Whose importance’ should be replaced with ‘the importance of which’. Since, ‘whose’ is not used for non living things",
						"48. (c); ‘his’ should be used in place of ‘their’ since, ‘either of’, ‘neither of’, ‘each of’, etc. are followed by plural noun/pronoun but the verb/ pronoun used in latter part of the sentence is always singular",
						"49. (b); ‘whose design’ should be replaced with ‘the design of which’For explanation refer to question 47",
						"50. (e); No error",
						"Thnx for Joining"
						
						
						
							]
