questions = [
			[ "  Quiz: Sub-Agrmt will start in 30 secs. " ],
									
			["1. (a) Neither of them/ (b) are going/(c) to take/(d) the exam on 4thMarch./ (e) No error"],
			["2. (a) She walked ten miles / (b) which are really a great distance/(c)for a woman like her /(d) who is not only old but also injured./(e)No error"],
			["3. (a) Either my father/(b) or my mother /(c) are going /(d) to attendmy cousin's wedding./(e) No error"],
			["4. (a) The rise and fall/ (b) of the share prices/(c) are due to /(d) policyparalyses on management's part./(e) No error"],
			["5. (a) Many a /(b)men have/(c) succumbed to/ (d) this temptation./(e) No error"],
			["6. (a) The invention of AC, T.V/(b)and such other appliances/(c) havenot been without /(d) some effect./ (e) No error"],
			["7. (a) Each of the students/ (b) in the science class has/(c) to preparetheir/(d) own research paper this semester./(e) No error"],
			["8. (a) Everyone of the novels/ (b)you suggested /(c) are not/(d) worthreading./ (e) No error"],
			["9. (a) There is/(b)only one of his/(c) movies, that/(d) are interesting./(e) No error"],
			["10. (a) Knowledge of/(b)at least two subjects/(c) are required to/(d)pass the examination./(e) No error"],
			["11. (a) It is I/(b) who is/(c) to blame/(d) for these complications./ (e)No error"],
			["12. (a)Patience as well as perseverance /(b) are necessary/(c) forsuccess./(d) in life. / (e) No error"],
			["13. (a)In Canada/(b)My brother with his wife/(c) were present/ (d) atthe function./(e) No error"],
			["14. (a)A hot and/(b)a cold spring/(c) is found /(d) near each other./(e)No error"],
			["15. (a)Neither of the/(b) paths/(c) lead/(d) to the school./(e) No error"],
			["16. (a)One of my ambitions/(b) are to become/(c) a cricketer/(d) oneday./(e) No error"],
			["17. (a)The whole block of flats/(b) including two clinics/ (c) weredestroyed/(d) in earthquake./ (e) No error"],
			["18. (a)Due to absence of any witness or evidence/(b)Neither of the/(c)five accused (d) could be convicted./ (e) No error"],
			["19. (a)The effect of all/ (b) the difficulties, vexations and anxieties/(c)were clearly visible /(d) on her face./ (e) No error"],
			["20. (a)Everything/(b) it must be admitted/(c) has their /(d) pros andcons./ (e) No error"],
			["21. (a)Every man in the world/(b) fervently hopes that their son/(c)will be a humble and kind man/(d) when he grows up./(e) No error"],
			["22. (a)Neither of them/(b) sent their quotations/(c) in time for/(d) thelast project./(e) No error"],
			["23. (a)This is a strange world/(b) where each one / (c) pursue their owndreams/(d) and laughs at others for doing the same./(e) No error"],
			["24. (a) A rise in/ (b) prices of metals and cars/(c) have been found/(d)to go together/(e) No error"],
			["25. (a) Kashmir is one of those few/ (b) place which provides/(c) adelightful escape from/(d) the strenuous life./(e) No error"],
			["26. (a) One of the peculiarities/ (b) which distinguishes/(c) the presentgeneration is/(d) its passion for achieving success./(e) No error"],
			["27. (a) Neither of them are /(b) going to have/(c) any problem as faras/(d) working in shifts is concerned/(e) No error"],
			["28. (a) If Martin Luther King/(b) was alive, he would feel sorry/(c) forthe destitute who/(d) still struggle everyday to make both endsmeet./(e) No error"],
			["29. (a)With regard to implementation of the/(b)the new laws passed inthe parliament,/(c) the committee was divided/(d) in their opinion./(e) No error"],
			["30. (a) Most of the funds/(b)we get from/(c)the centre is used to/(d)build roads, bridges and infrastructure./(e) No error"],
			["31. (a) He immediately quit/(b) the course in which the enhancementof/(c) neither growth nor placements/(d) were expected./(e) Noerror."],
			["32. (a) The sort of knowledge you acquire/ (b) depend upon the companyyou are in/(c) and so you associate/ (d) yourselves with sagaciousand good natured people./ (e) No error"],
			["33. (a) He is/(b) one of the most intelligent/(c) boy in/(d) the school./(e) No error"],
			["34. (a) That day when they/(b) brought him back, /(c) there was manyold-timers/(d) who were shocked and fearful./(e) No error"],
			["35. (a) I know that /(b) many a girl/(c) have not done their/(d)homework properly./ (e) No error"],
			["36. (a) Two miles beyond/(b) that building/(c) was seen/(d) thousandsof protesters. (e) No error"],
			["37. (a) A body of volunteers/(b) are responsible for /(c) making thispolitical rally/ (d) a great success./(e) No error"],
			["38. (a) There appears to be/ (b) large number of pathogens/(c) whichhave affected/(d) the immune system of the patient./(e) No error"],
			["39. (a) Measles are a disease/(b) in which a person develops/lots ofinflamed spots round the face. (e) No error"],
			["40. (a) Whether he should go for MBA/(b)or whether he /(c) shouldbecome a CA/(d) are his personal choice./(e) No error"],
			["41. (a) Many a/(b) men attended/(c) the party/(d) last month./ (e) Noerror."],
			["42. (a) The perquisites/ (b) to the government jobs/(c) makes them evenmore attractive/(d) than the salary indicated./ (e) No error"],
			["43. (a)Neither you/(b)nor she/(c) is /(d) happy./ (e) No error"],
			["44. (a) Rahul as well as/(b) his Parents/(c) have gone/(d) for the party./ (e) No error"],
			["45. (a) Bread and Butter/(b) are/(c) my favorite/(d) breakfast meal. /(e) No error"],
			["46. (a)Neither tea/(b) nor coffee nor sweets/(c) nor milk nor milkshake/(d) is liked by me. / (e) No error"],
			["47. (a) Sachin Tendulkar is one of those/(b) sportsperson who is/(c)regarded all /(d) over the world. / (e) No error"],
			["48. (a) I wish/(b) I was/(c) the President/(d) of India. / (e) No error"],
			["49. (a) Each of the/(b) boys have/(c) passed the/(d) entrance test. / (e)No error"],
			["50. (a) The request for reservation/(b) of the various minoritycommunities/(c) were supported /(d) by a vast majority. / (e) Noerror."],

									
			[ "Now OVER!!! Just rate us!"]
							]
						
		

	
				
				
				
sol=[				"Lets Start!",
					"1. (b); 'is' should be used in place of 'are'. Since, the 'noun' following 'neither' is plural, but the verb following the 'noun' should be singular",
					"2. (b); 'is' should be used in place of 'are'. Since ten miles is singular here (as it has been taken as a singular unit)",
					"3. (c); 'is' should be used in place of are. Since the verb used after 'eitheror'/ 'neither-nor' must agree with the nearest subject",
					"4. (c); 'is' should be used in place of 'are'. Since, 'The Rise and fall' denotes a singular subject",
					"5. (b); 'man' should be used in place of 'men' and 'has' should be used in place of 'have'. Since, 'Many a' is followed by a singular noun and singular verb",
					"6. (c); 'has' should be used in place of 'have'. Since 'invention' is a singular subject",
					"7. (c); 'his' should be used in place of 'their'. Since 'every/one/each etc. of is followed by a plural noun/pronoun but the verb as well as the pronoun used in remaining sentence is always singular",
					"8. (c); 'is' should be used in place of 'are'. Since 'Everyone' denotes a singular subject, hence, the verb which follows 'it' should also be singular",
					"9. (d); 'is' should be used in place of 'are' since 'one of' is a singular subject",
					"10. (c); 'is' should be used in place of 'are' since, 'knowledge' is the main subject of this sentence. Hence, singular verb should be used",
					"11. (b); 'am' should be used in place of 'is'. Since, when the subject and the verb are joined by a relative pronoun, the verb used should agree with the antecedent to the relative pronoun",
					"12. (b); 'is' should be used in place of 'are'. Since, when two subjects are joined by as well as, with, etc then the verb that follows should be in accordance with the former subject",
					"13. (c); 'Was' should be used in place of 'were' for explanation Refer to question -12",
					"14. (c); 'are' should be used in place of 'is' since, when two subjects are joined by 'and' and each subject is preceded by an article, then plural verb is used",
					"15. (c); 'leads' should be used in place of 'lead' for explanation refer to question-1",
					"16. (b); 'is' should be used in place of 'are'. For explanation refer to question -7",
					"17. (c); 'was' should be used in place of 'were' since the main subject (block) of the given sentence is singular. Hence, verb used should also be singular",
					"18. (b); 'None of' should be used in place of 'neither of' since, 'neither of' is used for 'two' whereas, none of' is used for more than two'",
					"19. (c); 'was' should be used in place of 'were'. Since, the main subject of the given subject is 'effect', which is singular. Hence, the verb which is used should also be singular",
					"20. (c); 'its' should be used in place of 'their'. Since 'everything' is a singular subject hence singular pronoun should be used",
					"21. (b); 'Every man' is singular and hence, singular verb and singular pronoun should be used. Hence, 'his' should be used in place of 'their'",
					"22. (b); 'his' should be used in place of 'their'. Since, 'neither of' is always followed by a plural noun/pronoun but the verb/pronoun used in the latter part of the sentence should be singular",
					"23. (c); 'pursues his' should be used in place of 'peruse their' since each one is singular subject, hence, 'singular verb and singular pronoun' should be used",
					"24. (c); 'has' should be used in place of 'have'. Since, the main subject of this sentence is 'rise'. Hence, singular verb should be used",
					"25. (b); 'one of' is followed by a 'plural noun' Hence 'places' should be used in place of 'place'. Now again the verb followed by relative pronoun must agree with the relative pronoun's antecedent (here, places). Hence, 'provide' should be used in place of 'provides'",
					"26. (b); 'distinguish' should be used in place of 'distinguishes'. (for explanation, refer to question 25)",
					"27. (a); 'is' should be used in place of 'are' for explanation refer to question – 22",
					"28. (b); 'were' should be used in place of 'was' since, in imaginary sentences, 'were' form of 'be' is used",
					"29. (c); 'were' should be used in place of 'was'. Since, when the members of collective noun act individually, then the collective noun is used as a plural subject and is followed by plural verbs and plural pronoun",
					"30. (c); 'are' should be used in place of 'is', since 'funds' is the main subject of the given sentence. Hence verb used should agree with the subject",
					"31. (d); 'was' should be used in place of 'were'. Since, the subject in the given sentence is 'enhancement' (which is singular). Hence, verb used should also be singular in order to agree with the subject",
					"32. (b); 'depends' should be used in place of 'depend' since, 'sort of _______' is singular. Hence, singular verb should be used",
					"33. (c); 'boys' should be used in place of 'boy'. Since 'one of _______' is followed by plural noun/pronoun",
					"34. (c); 'were' should be used in place of 'was'. Since, here verb must agree with first timers'",
					"35. (c); 'has' should be used in place of 'have' and 'her' should be used in place of 'their'. Since 'many a' is followed by a singular noun/ pronoun/verb",
					"36. (c); 'were' should be used in place of 'was'. since 'thousands of protesters' is the main subject of the given sentence, hence plural verb should be used",
					"37. (b); 'is' should be used in place of 'are'. Since collective noun like 'body' ,'team', 'group', 'class', etc. are used as singular subjects and hence, singular verb should be used with them",
					"38. (a); 'appear' should be used in place 'appears' since 'large number of pathogens' is the main subject in this sentence, which is plural, hence, plural verb should be used",
					"39. (a); 'measles' plural in form but singular in meaning. Thus, singular verb 'is' should be used place of 'are'",
					"40. (d); 'is' should be used in place of 'are'",
					"41. (b); 'many a' is always followed by a singular noun and singular verb. Hence 'man' should be used in place of 'men'",
					"42. (c); 'make' should be used in place of 'makes'. Since words like perquisites, scissors, tongs, trousers, etc. are used as plural subject, Hence plural verb should be used with it",
					"43. (e); No error",
					"44. (c); 'Has' should be used in place of 'have' for explanation refer to question-12",
					"45. (b); 'is' should be used in place of 'are'. Since, 'bread and butter' denotes a singular subject. Hence, singular verb should be use",
					"46. (e); No error. We can use more than one 'or' and 'nor' after 'either' and 'neither' respectively",
					"47. (b); 'sport-persons' should be used in place of 'sports person' and 'are' should be used in place of 'is'. For explanation, refer to Question-25",
					"48. (b); 'were' should be used in place of 'was' since, in imaginary sentences, 'were' form of 'be' is used",
					"49. (b); 'has' should be used in place of 'have'. Since, 'each of' is followed by a 'plural noun', but, singular pronoun and singular verb is used in the latter part of the sentence",
					"50. (c); 'was' should be used in place of 'were' since, 'request' (which is singular), is the main subject here, hence singular form of verb should be used",
					"Thnx for Joining"
						
	
							]				


