    
questions =	[
	             [ "   Verb Quiz:will start in 30 secs. " ],
						

				["1. (a) He is very / (b) drunk, so he / (c) cannot tell / (d) you his name. /(e) No error"],
				["2. (a) A few selfish leaders are / (b) bent to harm the / (c) very foundation/ (d) of the democracy. / (e) No error"],
				["3. (a) You should avoid / (b) to go to office as you / (c) have severe / (d) eye infection. / (e) No error"],
				["4. (a) Everyone considered him as / (b) a brave man / (c) but he fled from/ (d) the battlefield. / (e) No error"],
				["5. (a) My father does not / (b)  mind to be disturbed / (c) while he is reading/ (d) the newspaper. / (e) No error"],
				["6. (a) Perhaps you do not know / (b) I am having a car and a jeep / (c)besides a big house/ (d) in a good locality./ (e) No error"],
				["7. (a) I bade him / (b) to submit all the / (c) important documents / (d) before he left the job. / (e) No error"],
				["8. (a) Mrs Dorai would rather / (b) spend a quiet evening / (c) than attending/ (d) a party / (e) No error"],
				["9. (a) The life-guard would not / (b) let the children / (c) to swim at the/ (d) deep end of the pool. / (e) No error"],
				["10. (a) Walking along the / (b) bank of the river / (c) the road / (d) began to rise. / (e) No error"],
				["11. (a) His assistants have and / (b) are still doing / (c) excellent work/(d) for the organisation. / (e) No error"],
				["12. (a) After the teacher had told the boys / (b) how to pronounce theword / (c) all of them in one voice / (d) repeated the word again. / (e)No error"],
				["13. (a) I declined the invitation / (b) not because I did not / (c) want to go, but because / (d) I have no time. / (e) No error"],
				["14. (a) Even after sixty years of independence / (b) lakhs of people / (c) do not have / (d) bed to sleep / (e) No error"],
				["15. (a) It being a stormy night, / (b) you must thought of postponing / (c)all your programmes / (d) till tomorrow morning. / (e) No error"],
				["16. (a) We would also like to help you / (b) if you intend to execute / (c)such lofty plans for the welfare / (d) of the society./ (e) No error"],
				["17. (a) The unreasonable behavior / (b) of his daughter / (c) was thoroughly/ (d) upset Mr. Gupta./ (e) No error"],
				["18. (a) Rajan abided by all / (b) the rules which were / (c) explained to him / (d) before the programme. / (e) No error"],
				["19. (a) They did not came/ (b) out victorious, / (c) yet they were not disappointed / (d) rather satisfied because they had played well. / (e)No error"],
				["20. (a) He complained to the police / (b) that his briefcase had been stolen/ (c) and that was lift / (d) without any money. / (e) No error"],
				["21. (a) It is true / (b) that the poor is unable / (c) to get nourished / (d)food even today. / (e) No error"],
				["22. (a) Unless these differences / (b) will be resolved soon/ (c) there will be an adverse / (d) effect on foreign investment. / (e) No error"],
				["23. (a) His dishonest acts / (b) have made his / (c) parents bent / (d) their heads in shame. / (e) No error"],
				["24. (a) Though none of his so-called / (b) well  wishers / (c) forwarded to help, I helped him by/(d) completing his work on time. / (e) No error"],
				["25. (a) The number of / (b) ATMs are being/ (c)increased to serve / (d)customers better / (e) No error"],


				["1. You ______ brush your teeth after every meal.(a) may (b) should (c)might(d)shall (e) will"],
				["2. The boys ______ train hard if they want to win the competition.(a) ought to (b) can (c) shall(d) must (e) dare not"],
				["3. If it does not rain tomorrow, we ______ go for a picnic.(a) could (b) need to (c) cannot(d) would have (e) will have"],
				["4. ______ you like to join me for a trip up Cameron Highlands?(a) could (b) should (c) Would(d) can (e) might"],
				["5. You ______ pay $5 if you want to take part in the contest.(a) cannot (b) may not (c) shall(d) should (e) must"],
				["6. ______ I go to toilet please?(a) May (b) Might (c) Can(d) Will (e) Shall"],
				["7. Children ______ respect their elders.(a) Should (b) ought not to (c) must(d) Ought to (e) will"],
				["8. Mrs. Tay _______ leave for Bangkok tomorrow for a business meeting.(a) would (b) shall (c) should(d) will (e) may"],
				["9. I ______ take a holiday after working tirelessly on this project.(a) need to (b) dare to (c) might(d) may (e) need"],
				["10.Although Daniel is an obedient child, he ______ be rebellious attimes.(a) will (b) shall (c) should(d) would (e) can"],
				["11.Leela __________ not swim when she was one year old.(a) is (b) can (c) may(d) could (e) would"],
				["12. __________ I borrow your pen?(a) can (b) may (c) will(d) Shall (e) might"],
				["13. It's too cold. We __________ close the window.(a) must (b) should (c) ought to(d) can (e) may"],
				["14.We ________ watch television very much.(a) could not (b) should (c) may not(d) ought not to (e) will"],
				["15.You __________ leave the class early to catch the train.(a) could (b) will (c) should(d) may (e) might"],
				["16.He __________ play cricket before his marriage.(a) use to (b) used to (c) need to(d) should (e) ought to"],
				["17.She __________ be friendly, but she usually isn't.(a) might (b) may (c) can(d) could (e) will"],
				["18. I __________ leave now. My parents are waiting for me.(a) must (b) may (c) can(d) will (e) shall"],
				["19.Sammy __________ lift that heavy box. He is too small.(a) can (b) may (c) should not(d) cannot (e) will"],
				["20.You have not done so well. You __________ have studied harder.(a) need to (b) ought to (c) might(d) shall (e) will"],
				["21.He __________ run faster if he was not so lazy.(a) should (b) could (c) may(d) can (e) could"],
				["22.The project __________ be finished in two years time.(a) will (b) can (c) shall(d) should (e) would"],
				["23.He __________ not disobey his parents.(a) may (b) dare (c) dare not(d) will (e) should"],
				["24.Mustafa __________ come to the party, but nobody is sure.(a) might (b) may (c) will(d) should (e) would"],
				["25.They __________ be neighbours when they were young.(a) will (b) might (c) used to(d) shall (e) ought to"],

				[ "Now OVER!!! Just rate us!"]
							]
						
				

	
				
				
				
sol=[						"Lets Start!",
							"1. (d); No correction required",
							"2. (b); Change 'bent to harm' on 'bent to harming'. 'Bent on' means determined to do",
							"3. (b); Change 'to go' to 'going'. Gerund comes after 'avoid'",
							"4. (a); Remove 'as'. 'Considered' is not followed by 'as'",
							"5. (b); 'Gerund' will come after 'mind'. Change 'be' into 'being'",
							"6. (b); Change 'am having' into 'have'. When 'have' means 'to possess', it does not take 'ing' form",
							"7. (b); 'Bade' (V2 of bid) takes 'plain infinitive' (V1) after it and not 'infinitive' (to + V1). Change 'to submit' into 'submit'",
							"8. (c); Use 'attend' after 'than'. Because 'would rather' is followed by 'V1' and after 'than' the form 'V1 'will come",
							"9. (c); Use V1 after 'let'. Remove 'to'",
							"10. (a); Add 'while I was' before 'walking alone'",
							"11. (a); Add 'done' after 'have'. Different forms of verbs should be used in a sentence if required",
							"12. (a); Remove 'again'. 'Repeat' should not be followed by 'again' because this will make the sentence superfluous",
							"13. (d); Change 'have' to 'had'. The sentence is in past",
							"14. (c); Add 'in' after 'sleep'. If 'infinitive' is used after 'noun' then appropriate preposition should follow 'infinitive'",
							"15. (b); Change 'thought' to 'think' as 'must' is a modal which is always followed by V1",
							"16. (d); No correction required",
							"17. (c); Remove 'was' ",
							"18. (d); No correction required",
							"19. (a); Replace 'came' with 'come' as did not is always followed by V1",
							"20. (c); Replace 'lifted' with 'left' as 'lift' means raise to a higher position or level and 'left' means go away from",
							"21. (b); Replace 'is' with 'are' as here 'poor' stands for 'poor people'",
							"22. (b); Substitute 'are' for 'will be'. When two future events are to be expressed in a sentence the first event is expressed in simple present tense while the subsequent event is expressed in simple future tense. Hence first 'will be' should be replaced with 'are'",
							"23. (b); Replace 'bent' with 'bend'. When used as bare infinitive 'made' agrees with V1",
							"24. (b); Replace 'forwarded to help' with 'came for help'",
							"25. (b); Write 'ATM is' because 'the number' agrees with singular verb ",
							
							"1. (b); should ; Since, 'should' is used to show what is the correct or best thing to do",
							"2. (d); must ; Since, 'must' is used to show compulsion .",
							"3. (a); could ; Since, 'could' is used to show possibility.",
							"4. (c); Would ; Since, 'would' is used to take permission or ask preference.",
							"5. (e) must ; Since 'must' is used to denote compulsion.",
							"6. (a); May ; Since, 'may' is used to take permission.",
							"7. (d); Ought to; Since, 'ought to' is used to denote moral duty.",
							"8. (d); will ; For some future course of action, 'will' is used.",
							"9. (a); need to ; The main verb need is followed by 'to' when used with another verb.",
							"10. (e); can ; 'can' is used to show ability of a person.",
							"11. (d); could; Here, we need a modal verb which shows ability of Leela to swim, hence, 'can' and 'could' can be the correct option. But the phrase 'she was one year old' suggests that the modal to be used should be in past form, hence, 'could' is the most appropriate option.",
							"12. (b); may; 'May' is used to ask for taking permission.",
							"13. (a); must; 'must' is used to show some compulsion.",
							"14. (d); ought not to; ought not to is used to show when it is necessary or would be a good thing to not perform the activity referred to by the following verb.",
							"15. (c); should; 'should' is used to say or ask what is the correct or best thing to do.",
							"16. (b); used to; 'used to' is generally used to show some past habit.",
							"17. (d); could; 'could' is used to express possibility, especially slight or uncertain possibility.",
							"18. (a); must; 'must' is used to show that it is necessary or very important that something happens in the present or future",
							"19. (d); cannot; 'cannot' is the negative form of the verb 'can'. it is used to show the 'disability' of a person to do something",
							"20. (b); ought to; 'ought to' is the correct option.",
							"21. (e); could; 'could' is used to show ability of a person.",
							"22. (d); should; 'should' is also used to show possibility.",
							"23. (b); dare; 'dare' is the correct option.",
							"24. (a); might; 'might' is used to denote light possibility.",
							"25. (c); used to; 'used to' is used to denote some action which was 'done or experienced in the past'",
							"Thnx for Joining"
							

						
							]
			
